//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M001_Secimler : global::System.Configuration.ApplicationSettingsBase {
        
        private static M001_Secimler defaultInstance = ((M001_Secimler)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M001_Secimler())));
        
        public static M001_Secimler Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB2_Agrega1Calistir {
            get {
                return ((bool)(this["XB2_Agrega1Calistir"]));
            }
            set {
                this["XB2_Agrega1Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega2Calistir {
            get {
                return ((bool)(this["XB2_Agrega2Calistir"]));
            }
            set {
                this["XB2_Agrega2Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega3Calistir {
            get {
                return ((bool)(this["XB2_Agrega3Calistir"]));
            }
            set {
                this["XB2_Agrega3Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega4Calistir {
            get {
                return ((bool)(this["XB2_Agrega4Calistir"]));
            }
            set {
                this["XB2_Agrega4Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega5Calistir {
            get {
                return ((bool)(this["XB2_Agrega5Calistir"]));
            }
            set {
                this["XB2_Agrega5Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega6Calistir {
            get {
                return ((bool)(this["XB2_Agrega6Calistir"]));
            }
            set {
                this["XB2_Agrega6Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega7Calistir {
            get {
                return ((bool)(this["XB2_Agrega7Calistir"]));
            }
            set {
                this["XB2_Agrega7Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_Agrega8Calistir {
            get {
                return ((bool)(this["XB2_Agrega8Calistir"]));
            }
            set {
                this["XB2_Agrega8Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega1 {
            get {
                return ((bool)(this["XB2_DurAgrega1"]));
            }
            set {
                this["XB2_DurAgrega1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega2 {
            get {
                return ((bool)(this["XB2_DurAgrega2"]));
            }
            set {
                this["XB2_DurAgrega2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega3 {
            get {
                return ((bool)(this["XB2_DurAgrega3"]));
            }
            set {
                this["XB2_DurAgrega3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega4 {
            get {
                return ((bool)(this["XB2_DurAgrega4"]));
            }
            set {
                this["XB2_DurAgrega4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega5 {
            get {
                return ((bool)(this["XB2_DurAgrega5"]));
            }
            set {
                this["XB2_DurAgrega5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega6 {
            get {
                return ((bool)(this["XB2_DurAgrega6"]));
            }
            set {
                this["XB2_DurAgrega6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega7 {
            get {
                return ((bool)(this["XB2_DurAgrega7"]));
            }
            set {
                this["XB2_DurAgrega7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB2_DurAgrega8 {
            get {
                return ((bool)(this["XB2_DurAgrega8"]));
            }
            set {
                this["XB2_DurAgrega8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool AgregaDegistirmeIslemiTamamlaniyor {
            get {
                return ((bool)(this["AgregaDegistirmeIslemiTamamlaniyor"]));
            }
            set {
                this["AgregaDegistirmeIslemiTamamlaniyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S1Calistir {
            get {
                return ((bool)(this["XB3_S1Calistir"]));
            }
            set {
                this["XB3_S1Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S2Calistir {
            get {
                return ((bool)(this["XB3_S2Calistir"]));
            }
            set {
                this["XB3_S2Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S3Calistir {
            get {
                return ((bool)(this["XB3_S3Calistir"]));
            }
            set {
                this["XB3_S3Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S4Calistir {
            get {
                return ((bool)(this["XB3_S4Calistir"]));
            }
            set {
                this["XB3_S4Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S5Calistir {
            get {
                return ((bool)(this["XB3_S5Calistir"]));
            }
            set {
                this["XB3_S5Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_S6Calistir {
            get {
                return ((bool)(this["XB3_S6Calistir"]));
            }
            set {
                this["XB3_S6Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo1 {
            get {
                return ((bool)(this["XB3_DurSilo1"]));
            }
            set {
                this["XB3_DurSilo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo2 {
            get {
                return ((bool)(this["XB3_DurSilo2"]));
            }
            set {
                this["XB3_DurSilo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo3 {
            get {
                return ((bool)(this["XB3_DurSilo3"]));
            }
            set {
                this["XB3_DurSilo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo4 {
            get {
                return ((bool)(this["XB3_DurSilo4"]));
            }
            set {
                this["XB3_DurSilo4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo5 {
            get {
                return ((bool)(this["XB3_DurSilo5"]));
            }
            set {
                this["XB3_DurSilo5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB3_DurSilo6 {
            get {
                return ((bool)(this["XB3_DurSilo6"]));
            }
            set {
                this["XB3_DurSilo6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool SiloDegistirmeIslemiTamamlaniyor {
            get {
                return ((bool)(this["SiloDegistirmeIslemiTamamlaniyor"]));
            }
            set {
                this["SiloDegistirmeIslemiTamamlaniyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki1Calistir {
            get {
                return ((bool)(this["XB5_Katki1Calistir"]));
            }
            set {
                this["XB5_Katki1Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki2Calistir {
            get {
                return ((bool)(this["XB5_Katki2Calistir"]));
            }
            set {
                this["XB5_Katki2Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki3Calistir {
            get {
                return ((bool)(this["XB5_Katki3Calistir"]));
            }
            set {
                this["XB5_Katki3Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki4Calistir {
            get {
                return ((bool)(this["XB5_Katki4Calistir"]));
            }
            set {
                this["XB5_Katki4Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki5Calistir {
            get {
                return ((bool)(this["XB5_Katki5Calistir"]));
            }
            set {
                this["XB5_Katki5Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_Katki6Calistir {
            get {
                return ((bool)(this["XB5_Katki6Calistir"]));
            }
            set {
                this["XB5_Katki6Calistir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki1 {
            get {
                return ((bool)(this["XB5_DurKatki1"]));
            }
            set {
                this["XB5_DurKatki1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki2 {
            get {
                return ((bool)(this["XB5_DurKatki2"]));
            }
            set {
                this["XB5_DurKatki2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki3 {
            get {
                return ((bool)(this["XB5_DurKatki3"]));
            }
            set {
                this["XB5_DurKatki3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki4 {
            get {
                return ((bool)(this["XB5_DurKatki4"]));
            }
            set {
                this["XB5_DurKatki4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki5 {
            get {
                return ((bool)(this["XB5_DurKatki5"]));
            }
            set {
                this["XB5_DurKatki5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool XB5_DurKatki6 {
            get {
                return ((bool)(this["XB5_DurKatki6"]));
            }
            set {
                this["XB5_DurKatki6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool KatkiDegistirmeIslemiTamamlaniyor {
            get {
                return ((bool)(this["KatkiDegistirmeIslemiTamamlaniyor"]));
            }
            set {
                this["KatkiDegistirmeIslemiTamamlaniyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Spare_1 {
            get {
                return ((bool)(this["Spare_1"]));
            }
            set {
                this["Spare_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Spare_2 {
            get {
                return ((bool)(this["Spare_2"]));
            }
            set {
                this["Spare_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Spare_3 {
            get {
                return ((bool)(this["Spare_3"]));
            }
            set {
                this["Spare_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Spare_4 {
            get {
                return ((bool)(this["Spare_4"]));
            }
            set {
                this["Spare_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Spare_5 {
            get {
                return ((bool)(this["Spare_5"]));
            }
            set {
                this["Spare_5"] = value;
            }
        }
    }
}
