//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M002_YariOto : global::System.Configuration.ApplicationSettingsBase {
        
        private static M002_YariOto defaultInstance = ((M002_YariOto)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M002_YariOto())));
        
        public static M002_YariOto Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoAgregaAlim {
            get {
                return ((bool)(this["v_YariOtoAgregaAlim"]));
            }
            set {
                this["v_YariOtoAgregaAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoCimentoAlim {
            get {
                return ((bool)(this["v_YariOtoCimentoAlim"]));
            }
            set {
                this["v_YariOtoCimentoAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoKatkiAlim {
            get {
                return ((bool)(this["v_YariOtoKatkiAlim"]));
            }
            set {
                this["v_YariOtoKatkiAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoAgregaAlimStop {
            get {
                return ((bool)(this["v_YariOtoAgregaAlimStop"]));
            }
            set {
                this["v_YariOtoAgregaAlimStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoCimentoAlimStop {
            get {
                return ((bool)(this["v_YariOtoCimentoAlimStop"]));
            }
            set {
                this["v_YariOtoCimentoAlimStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoSuAlimStop {
            get {
                return ((bool)(this["v_YariOtoSuAlimStop"]));
            }
            set {
                this["v_YariOtoSuAlimStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoKatkiAlimStop {
            get {
                return ((bool)(this["v_YariOtoKatkiAlimStop"]));
            }
            set {
                this["v_YariOtoKatkiAlimStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_6 {
            get {
                return ((bool)(this["Spare_6"]));
            }
            set {
                this["Spare_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_7 {
            get {
                return ((bool)(this["Spare_7"]));
            }
            set {
                this["Spare_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_8 {
            get {
                return ((bool)(this["Spare_8"]));
            }
            set {
                this["Spare_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_9 {
            get {
                return ((bool)(this["Spare_9"]));
            }
            set {
                this["Spare_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_10 {
            get {
                return ((bool)(this["Spare_10"]));
            }
            set {
                this["Spare_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_11 {
            get {
                return ((bool)(this["Spare_11"]));
            }
            set {
                this["Spare_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_YariOtoSuAlim {
            get {
                return ((bool)(this["v_YariOtoSuAlim"]));
            }
            set {
                this["v_YariOtoSuAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_12 {
            get {
                return ((bool)(this["Spare_12"]));
            }
            set {
                this["Spare_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_13 {
            get {
                return ((bool)(this["Spare_13"]));
            }
            set {
                this["Spare_13"] = value;
            }
        }
    }
}
