//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M005_Modbus : global::System.Configuration.ApplicationSettingsBase {
        
        private static M005_Modbus defaultInstance = ((M005_Modbus)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M005_Modbus())));
        
        public static M005_Modbus Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_KalibreSon {
            get {
                return ((bool)(this["XB159_KalibreSon"]));
            }
            set {
                this["XB159_KalibreSon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_KantarSifirla {
            get {
                return ((bool)(this["XB159_KantarSifirla"]));
            }
            set {
                this["XB159_KantarSifirla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_KantarAgirliginiYaz {
            get {
                return ((bool)(this["XB159_KantarAgirliginiYaz"]));
            }
            set {
                this["XB159_KantarAgirliginiYaz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_AgSec {
            get {
                return ((bool)(this["XB159_AgSec"]));
            }
            set {
                this["XB159_AgSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_CimSec {
            get {
                return ((bool)(this["XB159_CimSec"]));
            }
            set {
                this["XB159_CimSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_SuSec {
            get {
                return ((bool)(this["XB159_SuSec"]));
            }
            set {
                this["XB159_SuSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_KatkiSec {
            get {
                return ((bool)(this["XB159_KatkiSec"]));
            }
            set {
                this["XB159_KatkiSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_SlumpHesapla {
            get {
                return ((bool)(this["XB159_SlumpHesapla"]));
            }
            set {
                this["XB159_SlumpHesapla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB159_TusKilitle {
            get {
                return ((bool)(this["XB159_TusKilitle"]));
            }
            set {
                this["XB159_TusKilitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KalibrasyonYapilacak {
            get {
                return ((bool)(this["KalibrasyonYapilacak"]));
            }
            set {
                this["KalibrasyonYapilacak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TusKilitlemeYapilacak {
            get {
                return ((bool)(this["TusKilitlemeYapilacak"]));
            }
            set {
                this["TusKilitlemeYapilacak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_SetpointSendRunning {
            get {
                return ((bool)(this["v_SetpointSendRunning"]));
            }
            set {
                this["v_SetpointSendRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_63 {
            get {
                return ((bool)(this["Spare_63"]));
            }
            set {
                this["Spare_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_64 {
            get {
                return ((bool)(this["Spare_64"]));
            }
            set {
                this["Spare_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_65 {
            get {
                return ((bool)(this["Spare_65"]));
            }
            set {
                this["Spare_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_66 {
            get {
                return ((bool)(this["Spare_66"]));
            }
            set {
                this["Spare_66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_67 {
            get {
                return ((bool)(this["Spare_67"]));
            }
            set {
                this["Spare_67"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_68 {
            get {
                return ((bool)(this["Spare_68"]));
            }
            set {
                this["Spare_68"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_69 {
            get {
                return ((bool)(this["Spare_69"]));
            }
            set {
                this["Spare_69"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_70 {
            get {
                return ((bool)(this["Spare_70"]));
            }
            set {
                this["Spare_70"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_71 {
            get {
                return ((bool)(this["Spare_71"]));
            }
            set {
                this["Spare_71"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_72 {
            get {
                return ((bool)(this["Spare_72"]));
            }
            set {
                this["Spare_72"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_73 {
            get {
                return ((bool)(this["Spare_73"]));
            }
            set {
                this["Spare_73"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_74 {
            get {
                return ((bool)(this["Spare_74"]));
            }
            set {
                this["Spare_74"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_75 {
            get {
                return ((bool)(this["Spare_75"]));
            }
            set {
                this["Spare_75"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_76 {
            get {
                return ((bool)(this["Spare_76"]));
            }
            set {
                this["Spare_76"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_77 {
            get {
                return ((bool)(this["Spare_77"]));
            }
            set {
                this["Spare_77"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_78 {
            get {
                return ((bool)(this["Spare_78"]));
            }
            set {
                this["Spare_78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_79 {
            get {
                return ((bool)(this["Spare_79"]));
            }
            set {
                this["Spare_79"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_80 {
            get {
                return ((bool)(this["Spare_80"]));
            }
            set {
                this["Spare_80"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_81 {
            get {
                return ((bool)(this["Spare_81"]));
            }
            set {
                this["Spare_81"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_82 {
            get {
                return ((bool)(this["Spare_82"]));
            }
            set {
                this["Spare_82"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB159_KalibrasyonAgirligi {
            get {
                return ((int)(this["XB159_KalibrasyonAgirligi"]));
            }
            set {
                this["XB159_KalibrasyonAgirligi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_MikserSlump {
            get {
                return ((double)(this["XB1_MikserSlump"]));
            }
            set {
                this["XB1_MikserSlump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_VoltajOrtalama {
            get {
                return ((double)(this["XB1_VoltajOrtalama"]));
            }
            set {
                this["XB1_VoltajOrtalama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_VoltajAra {
            get {
                return ((double)(this["XB1_VoltajAra"]));
            }
            set {
                this["XB1_VoltajAra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_HelezonAkimAra {
            get {
                return ((double)(this["XB1_HelezonAkimAra"]));
            }
            set {
                this["XB1_HelezonAkimAra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_Frekans {
            get {
                return ((double)(this["XB1_Frekans"]));
            }
            set {
                this["XB1_Frekans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_ToplamAkim {
            get {
                return ((double)(this["XB1_ToplamAkim"]));
            }
            set {
                this["XB1_ToplamAkim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_Voltaj1 {
            get {
                return ((double)(this["XB1_Voltaj1"]));
            }
            set {
                this["XB1_Voltaj1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_Voltaj2 {
            get {
                return ((double)(this["XB1_Voltaj2"]));
            }
            set {
                this["XB1_Voltaj2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_Voltaj3 {
            get {
                return ((double)(this["XB1_Voltaj3"]));
            }
            set {
                this["XB1_Voltaj3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB159_Kalibrasyon_Agirligi {
            get {
                return ((double)(this["XB159_Kalibrasyon_Agirligi"]));
            }
            set {
                this["XB159_Kalibrasyon_Agirligi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Setting {
            get {
                return ((double)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB158_KantarAdresi {
            get {
                return ((int)(this["XB158_KantarAdresi"]));
            }
            set {
                this["XB158_KantarAdresi"] = value;
            }
        }
    }
}
