//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M006_Uretim : global::System.Configuration.ApplicationSettingsBase {
        
        private static M006_Uretim defaultInstance = ((M006_Uretim)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M006_Uretim())));
        
        public static M006_Uretim Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_UretimBittiKayitReset {
            get {
                return ((bool)(this["XB111_UretimBittiKayitReset"]));
            }
            set {
                this["XB111_UretimBittiKayitReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AraKayitAl {
            get {
                return ((bool)(this["AraKayitAl"]));
            }
            set {
                this["AraKayitAl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB101_GonderAnimasyon {
            get {
                return ((bool)(this["XB101_GonderAnimasyon"]));
            }
            set {
                this["XB101_GonderAnimasyon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerilerPLCdenGonderildi {
            get {
                return ((bool)(this["VerilerPLCdenGonderildi"]));
            }
            set {
                this["VerilerPLCdenGonderildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerilerResetDelay {
            get {
                return ((bool)(this["VerilerResetDelay"]));
            }
            set {
                this["VerilerResetDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IrsaliyeYazdir {
            get {
                return ((bool)(this["IrsaliyeYazdir"]));
            }
            set {
                this["IrsaliyeYazdir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_Reset {
            get {
                return ((bool)(this["XB1_Reset"]));
            }
            set {
                this["XB1_Reset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_StartOK {
            get {
                return ((bool)(this["XB1_StartOK"]));
            }
            set {
                this["XB1_StartOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_Gonder {
            get {
                return ((bool)(this["XB1_Gonder"]));
            }
            set {
                this["XB1_Gonder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_KornaBaslangic {
            get {
                return ((bool)(this["XB1_KornaBaslangic"]));
            }
            set {
                this["XB1_KornaBaslangic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_KornaBitis {
            get {
                return ((bool)(this["XB1_KornaBitis"]));
            }
            set {
                this["XB1_KornaBitis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_BosaltmaBitti {
            get {
                return ((bool)(this["XB1_BosaltmaBitti"]));
            }
            set {
                this["XB1_BosaltmaBitti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_KontrolWordlerSifir {
            get {
                return ((bool)(this["XB1_KontrolWordlerSifir"]));
            }
            set {
                this["XB1_KontrolWordlerSifir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_CimSuKatAlindi {
            get {
                return ((bool)(this["XB1_CimSuKatAlindi"]));
            }
            set {
                this["XB1_CimSuKatAlindi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_MikserStart {
            get {
                return ((bool)(this["XB1_MikserStart"]));
            }
            set {
                this["XB1_MikserStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB1_24VFren_Gecis {
            get {
                return ((bool)(this["XB1_24VFren_Gecis"]));
            }
            set {
                this["XB1_24VFren_Gecis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_83 {
            get {
                return ((bool)(this["Spare_83"]));
            }
            set {
                this["Spare_83"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_84 {
            get {
                return ((bool)(this["Spare_84"]));
            }
            set {
                this["Spare_84"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_85 {
            get {
                return ((bool)(this["Spare_85"]));
            }
            set {
                this["Spare_85"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_86 {
            get {
                return ((bool)(this["Spare_86"]));
            }
            set {
                this["Spare_86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_87 {
            get {
                return ((bool)(this["Spare_87"]));
            }
            set {
                this["Spare_87"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_88 {
            get {
                return ((bool)(this["Spare_88"]));
            }
            set {
                this["Spare_88"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_89 {
            get {
                return ((bool)(this["Spare_89"]));
            }
            set {
                this["Spare_89"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_90 {
            get {
                return ((bool)(this["Spare_90"]));
            }
            set {
                this["Spare_90"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_91 {
            get {
                return ((bool)(this["Spare_91"]));
            }
            set {
                this["Spare_91"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_92 {
            get {
                return ((bool)(this["Spare_92"]));
            }
            set {
                this["Spare_92"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_93 {
            get {
                return ((bool)(this["Spare_93"]));
            }
            set {
                this["Spare_93"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_94 {
            get {
                return ((bool)(this["Spare_94"]));
            }
            set {
                this["Spare_94"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_95 {
            get {
                return ((bool)(this["Spare_95"]));
            }
            set {
                this["Spare_95"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_96 {
            get {
                return ((bool)(this["Spare_96"]));
            }
            set {
                this["Spare_96"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_97 {
            get {
                return ((bool)(this["Spare_97"]));
            }
            set {
                this["Spare_97"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB1_KovaYukBekKalanSure {
            get {
                return ((int)(this["XB1_KovaYukBekKalanSure"]));
            }
            set {
                this["XB1_KovaYukBekKalanSure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB1_MikserKalanSure {
            get {
                return ((int)(this["XB1_MikserKalanSure"]));
            }
            set {
                this["XB1_MikserKalanSure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB1_MikserKapakAcikKalmaSure {
            get {
                return ((int)(this["XB1_MikserKapakAcikKalmaSure"]));
            }
            set {
                this["XB1_MikserKapakAcikKalmaSure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_SoklamaKW {
            get {
                return ((int)(this["XB112_SoklamaKW"]));
            }
            set {
                this["XB112_SoklamaKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_MikserAnalogDeger {
            get {
                return ((double)(this["XB19_MikserAnalogDeger"]));
            }
            set {
                this["XB19_MikserAnalogDeger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SiradakiPlanaGecisYapilacak {
            get {
                return ((bool)(this["SiradakiPlanaGecisYapilacak"]));
            }
            set {
                this["SiradakiPlanaGecisYapilacak"] = value;
            }
        }
    }
}
