//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M007_Cfg : global::System.Configuration.ApplicationSettingsBase {
        
        private static M007_Cfg defaultInstance = ((M007_Cfg)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M007_Cfg())));
        
        public static M007_Cfg Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaAsagidaS {
            get {
                return ((bool)(this["i_KovaAsagidaS"]));
            }
            set {
                this["i_KovaAsagidaS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaYukaridaS {
            get {
                return ((bool)(this["i_KovaYukaridaS"]));
            }
            set {
                this["i_KovaYukaridaS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaOrtaLimit {
            get {
                return ((bool)(this["i_KovaOrtaLimit"]));
            }
            set {
                this["i_KovaOrtaLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaAsagidaYavaslamaS {
            get {
                return ((bool)(this["i_KovaAsagidaYavaslamaS"]));
            }
            set {
                this["i_KovaAsagidaYavaslamaS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_FrenAcik {
            get {
                return ((bool)(this["i_FrenAcik"]));
            }
            set {
                this["i_FrenAcik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_GenelEmniyet {
            get {
                return ((bool)(this["i_GenelEmniyet"]));
            }
            set {
                this["i_GenelEmniyet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaYukariYavasCalisiyor {
            get {
                return ((bool)(this["i_KovaYukariYavasCalisiyor"]));
            }
            set {
                this["i_KovaYukariYavasCalisiyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaAsagiHizli {
            get {
                return ((bool)(this["i_KovaAsagiHizli"]));
            }
            set {
                this["i_KovaAsagiHizli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaAsagiYavas {
            get {
                return ((bool)(this["i_KovaAsagiYavas"]));
            }
            set {
                this["i_KovaAsagiYavas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_KovaTermikAriza {
            get {
                return ((bool)(this["i_KovaTermikAriza"]));
            }
            set {
                this["i_KovaTermikAriza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_KovaYukariStart {
            get {
                return ((bool)(this["q_KovaYukariStart"]));
            }
            set {
                this["q_KovaYukariStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_KovaAsagiStart {
            get {
                return ((bool)(this["q_KovaAsagiStart"]));
            }
            set {
                this["q_KovaAsagiStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_KovaAsagiYavasStart {
            get {
                return ((bool)(this["q_KovaAsagiYavasStart"]));
            }
            set {
                this["q_KovaAsagiYavasStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_KovaYukari24VFren {
            get {
                return ((bool)(this["q_KovaYukari24VFren"]));
            }
            set {
                this["q_KovaYukari24VFren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Yrd_SkipYukari {
            get {
                return ((bool)(this["v_Yrd_SkipYukari"]));
            }
            set {
                this["v_Yrd_SkipYukari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Yrd_SkipAsagi {
            get {
                return ((bool)(this["v_Yrd_SkipAsagi"]));
            }
            set {
                this["v_Yrd_SkipAsagi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_TransferBantTermikAriza {
            get {
                return ((bool)(this["i_TransferBantTermikAriza"]));
            }
            set {
                this["i_TransferBantTermikAriza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_TransferBantiCalisiyor {
            get {
                return ((bool)(this["i_TransferBantiCalisiyor"]));
            }
            set {
                this["i_TransferBantiCalisiyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_TransferBandPullCordSwitch {
            get {
                return ((bool)(this["i_TransferBandPullCordSwitch"]));
            }
            set {
                this["i_TransferBandPullCordSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_BiriktirmeBunkerikapakAcik {
            get {
                return ((bool)(this["i_BiriktirmeBunkerikapakAcik"]));
            }
            set {
                this["i_BiriktirmeBunkerikapakAcik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_BiriktirmeBunkerikapakKapali {
            get {
                return ((bool)(this["i_BiriktirmeBunkerikapakKapali"]));
            }
            set {
                this["i_BiriktirmeBunkerikapakKapali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_BiriktirmeBunkeriVibratorTermikAriza {
            get {
                return ((bool)(this["i_BiriktirmeBunkeriVibratorTermikAriza"]));
            }
            set {
                this["i_BiriktirmeBunkeriVibratorTermikAriza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_BiriktirmeBunkeriCalisiyor {
            get {
                return ((bool)(this["i_BiriktirmeBunkeriCalisiyor"]));
            }
            set {
                this["i_BiriktirmeBunkeriCalisiyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool i_BiriktirmeBunkeriVibratorCalisiyor {
            get {
                return ((bool)(this["i_BiriktirmeBunkeriVibratorCalisiyor"]));
            }
            set {
                this["i_BiriktirmeBunkeriVibratorCalisiyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_TransferBandCalis {
            get {
                return ((bool)(this["q_TransferBandCalis"]));
            }
            set {
                this["q_TransferBandCalis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_BiriktirmeBunkeriCalis {
            get {
                return ((bool)(this["q_BiriktirmeBunkeriCalis"]));
            }
            set {
                this["q_BiriktirmeBunkeriCalis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool q_BiriktirmeBunkeriVibCalis {
            get {
                return ((bool)(this["q_BiriktirmeBunkeriVibCalis"]));
            }
            set {
                this["q_BiriktirmeBunkeriVibCalis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Yrd_TransferBandStart {
            get {
                return ((bool)(this["v_Yrd_TransferBandStart"]));
            }
            set {
                this["v_Yrd_TransferBandStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Yrd_TransferBandStop {
            get {
                return ((bool)(this["v_Yrd_TransferBandStop"]));
            }
            set {
                this["v_Yrd_TransferBandStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_98 {
            get {
                return ((bool)(this["Spare_98"]));
            }
            set {
                this["Spare_98"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_99 {
            get {
                return ((bool)(this["Spare_99"]));
            }
            set {
                this["Spare_99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_100 {
            get {
                return ((bool)(this["Spare_100"]));
            }
            set {
                this["Spare_100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_101 {
            get {
                return ((bool)(this["Spare_101"]));
            }
            set {
                this["Spare_101"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_102 {
            get {
                return ((bool)(this["Spare_102"]));
            }
            set {
                this["Spare_102"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_103 {
            get {
                return ((bool)(this["Spare_103"]));
            }
            set {
                this["Spare_103"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_104 {
            get {
                return ((bool)(this["Spare_104"]));
            }
            set {
                this["Spare_104"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_105 {
            get {
                return ((bool)(this["Spare_105"]));
            }
            set {
                this["Spare_105"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_106 {
            get {
                return ((bool)(this["Spare_106"]));
            }
            set {
                this["Spare_106"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_107 {
            get {
                return ((bool)(this["Spare_107"]));
            }
            set {
                this["Spare_107"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_108 {
            get {
                return ((bool)(this["Spare_108"]));
            }
            set {
                this["Spare_108"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_109 {
            get {
                return ((bool)(this["Spare_109"]));
            }
            set {
                this["Spare_109"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_110 {
            get {
                return ((bool)(this["Spare_110"]));
            }
            set {
                this["Spare_110"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_111 {
            get {
                return ((bool)(this["Spare_111"]));
            }
            set {
                this["Spare_111"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_112 {
            get {
                return ((bool)(this["Spare_112"]));
            }
            set {
                this["Spare_112"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_113 {
            get {
                return ((bool)(this["Spare_113"]));
            }
            set {
                this["Spare_113"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_114 {
            get {
                return ((bool)(this["Spare_114"]));
            }
            set {
                this["Spare_114"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_115 {
            get {
                return ((bool)(this["Spare_115"]));
            }
            set {
                this["Spare_115"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_116 {
            get {
                return ((bool)(this["Spare_116"]));
            }
            set {
                this["Spare_116"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_117 {
            get {
                return ((bool)(this["Spare_117"]));
            }
            set {
                this["Spare_117"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_118 {
            get {
                return ((bool)(this["Spare_118"]));
            }
            set {
                this["Spare_118"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_119 {
            get {
                return ((bool)(this["Spare_119"]));
            }
            set {
                this["Spare_119"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_120 {
            get {
                return ((bool)(this["Spare_120"]));
            }
            set {
                this["Spare_120"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_121 {
            get {
                return ((bool)(this["Spare_121"]));
            }
            set {
                this["Spare_121"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_122 {
            get {
                return ((bool)(this["Spare_122"]));
            }
            set {
                this["Spare_122"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_123 {
            get {
                return ((bool)(this["Spare_123"]));
            }
            set {
                this["Spare_123"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_124 {
            get {
                return ((bool)(this["Spare_124"]));
            }
            set {
                this["Spare_124"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_125 {
            get {
                return ((bool)(this["Spare_125"]));
            }
            set {
                this["Spare_125"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_126 {
            get {
                return ((bool)(this["Spare_126"]));
            }
            set {
                this["Spare_126"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_127 {
            get {
                return ((bool)(this["Spare_127"]));
            }
            set {
                this["Spare_127"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_128 {
            get {
                return ((bool)(this["Spare_128"]));
            }
            set {
                this["Spare_128"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_129 {
            get {
                return ((bool)(this["Spare_129"]));
            }
            set {
                this["Spare_129"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_130 {
            get {
                return ((bool)(this["Spare_130"]));
            }
            set {
                this["Spare_130"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_131 {
            get {
                return ((bool)(this["Spare_131"]));
            }
            set {
                this["Spare_131"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_132 {
            get {
                return ((bool)(this["Spare_132"]));
            }
            set {
                this["Spare_132"] = value;
            }
        }
    }
}
