//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M009_HMI : global::System.Configuration.ApplicationSettingsBase {
        
        private static M009_HMI defaultInstance = ((M009_HMI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M009_HMI())));
        
        public static M009_HMI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_SuKlepeKapali {
            get {
                return ((bool)(this["HMI_SuKlepeKapali"]));
            }
            set {
                this["HMI_SuKlepeKapali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_CimentoKlepeKapali {
            get {
                return ((bool)(this["HMI_CimentoKlepeKapali"]));
            }
            set {
                this["HMI_CimentoKlepeKapali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_MikserKapakAcik {
            get {
                return ((bool)(this["HMI_MikserKapakAcik"]));
            }
            set {
                this["HMI_MikserKapakAcik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_MikserKapakKapali {
            get {
                return ((bool)(this["HMI_MikserKapakKapali"]));
            }
            set {
                this["HMI_MikserKapakKapali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_SimTestAktif {
            get {
                return ((bool)(this["HMI_SimTestAktif"]));
            }
            set {
                this["HMI_SimTestAktif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_ButonOtomatikte {
            get {
                return ((bool)(this["HMI_ButonOtomatikte"]));
            }
            set {
                this["HMI_ButonOtomatikte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_ButonManualde {
            get {
                return ((bool)(this["HMI_ButonManualde"]));
            }
            set {
                this["HMI_ButonManualde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_ModYariOtomatik {
            get {
                return ((bool)(this["HMI_ModYariOtomatik"]));
            }
            set {
                this["HMI_ModYariOtomatik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_MikserKapakAcValf {
            get {
                return ((bool)(this["HMI_MikserKapakAcValf"]));
            }
            set {
                this["HMI_MikserKapakAcValf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_MikserKapakKapatValf {
            get {
                return ((bool)(this["HMI_MikserKapakKapatValf"]));
            }
            set {
                this["HMI_MikserKapakKapatValf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_CimentoBosalt {
            get {
                return ((bool)(this["HMI_CimentoBosalt"]));
            }
            set {
                this["HMI_CimentoBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_SuBosalt {
            get {
                return ((bool)(this["HMI_SuBosalt"]));
            }
            set {
                this["HMI_SuBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_KatkiBosalt {
            get {
                return ((bool)(this["HMI_KatkiBosalt"]));
            }
            set {
                this["HMI_KatkiBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_KovaAsagida {
            get {
                return ((bool)(this["HMI_KovaAsagida"]));
            }
            set {
                this["HMI_KovaAsagida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_KovaYukarida {
            get {
                return ((bool)(this["HMI_KovaYukarida"]));
            }
            set {
                this["HMI_KovaYukarida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_KovaOrtada {
            get {
                return ((bool)(this["HMI_KovaOrtada"]));
            }
            set {
                this["HMI_KovaOrtada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_KovaYavaslama {
            get {
                return ((bool)(this["HMI_KovaYavaslama"]));
            }
            set {
                this["HMI_KovaYavaslama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_AsagiHizliStart {
            get {
                return ((bool)(this["HMI_AsagiHizliStart"]));
            }
            set {
                this["HMI_AsagiHizliStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_YukariStart {
            get {
                return ((bool)(this["HMI_YukariStart"]));
            }
            set {
                this["HMI_YukariStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_AsagiYavasStart {
            get {
                return ((bool)(this["HMI_AsagiYavasStart"]));
            }
            set {
                this["HMI_AsagiYavasStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_FrenAcik {
            get {
                return ((bool)(this["HMI_FrenAcik"]));
            }
            set {
                this["HMI_FrenAcik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_48V {
            get {
                return ((bool)(this["HMI_48V"]));
            }
            set {
                this["HMI_48V"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HMI_24V {
            get {
                return ((bool)(this["HMI_24V"]));
            }
            set {
                this["HMI_24V"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_149 {
            get {
                return ((bool)(this["Spare_149"]));
            }
            set {
                this["Spare_149"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_150 {
            get {
                return ((bool)(this["Spare_150"]));
            }
            set {
                this["Spare_150"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_151 {
            get {
                return ((bool)(this["Spare_151"]));
            }
            set {
                this["Spare_151"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_152 {
            get {
                return ((bool)(this["Spare_152"]));
            }
            set {
                this["Spare_152"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_153 {
            get {
                return ((bool)(this["Spare_153"]));
            }
            set {
                this["Spare_153"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_154 {
            get {
                return ((bool)(this["Spare_154"]));
            }
            set {
                this["Spare_154"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_155 {
            get {
                return ((bool)(this["Spare_155"]));
            }
            set {
                this["Spare_155"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_156 {
            get {
                return ((bool)(this["Spare_156"]));
            }
            set {
                this["Spare_156"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_157 {
            get {
                return ((bool)(this["Spare_157"]));
            }
            set {
                this["Spare_157"] = value;
            }
        }
    }
}
