//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M010_Alarm : global::System.Configuration.ApplicationSettingsBase {
        
        private static M010_Alarm defaultInstance = ((M010_Alarm)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M010_Alarm())));
        
        public static M010_Alarm Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_O110_MikserCalismiyor {
            get {
                return ((bool)(this["AL_O110_MikserCalismiyor"]));
            }
            set {
                this["AL_O110_MikserCalismiyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_G109_XB46_MikserBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi {
            get {
                return ((bool)(this["AL_G109_XB46_MikserBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"]));
            }
            set {
                this["AL_G109_XB46_MikserBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A200_1_TartiKonveyor1MotorTMSArizasi {
            get {
                return ((bool)(this["AL_A200_1_TartiKonveyor1MotorTMSArizasi"]));
            }
            set {
                this["AL_A200_1_TartiKonveyor1MotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A100_MikserMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A100_MikserMotorTMSArizasi"]));
            }
            set {
                this["AL_A100_MikserMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A900_KompresorMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A900_KompresorMotorTMSArizasi"]));
            }
            set {
                this["AL_A900_KompresorMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_G507_CimentoKantariBosaltmaKapagiGriilenMaksimumSureIcindeAcilamadiKapanamadi {
            get {
                return ((bool)(this["AL_G507_CimentoKantariBosaltmaKapagiGriilenMaksimumSureIcindeAcilamadiKapanamadi"]));
            }
            set {
                this["AL_G507_CimentoKantariBosaltmaKapagiGriilenMaksimumSureIcindeAcilamadiKapanamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_G604_SuKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi {
            get {
                return ((bool)(this["AL_G604_SuKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"]));
            }
            set {
                this["AL_G604_SuKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_G704_KatkiKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi {
            get {
                return ((bool)(this["AL_G704_KatkiKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"]));
            }
            set {
                this["AL_G704_KatkiKantariBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_C204_TartiKonveyorAsiriYukArizasi {
            get {
                return ((bool)(this["AL_C204_TartiKonveyorAsiriYukArizasi"]));
            }
            set {
                this["AL_C204_TartiKonveyorAsiriYukArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_C503_CimentoKantariAsiriYukHatasi {
            get {
                return ((bool)(this["AL_C503_CimentoKantariAsiriYukHatasi"]));
            }
            set {
                this["AL_C503_CimentoKantariAsiriYukHatasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_C601_SuKantariAsiriYukHatasi {
            get {
                return ((bool)(this["AL_C601_SuKantariAsiriYukHatasi"]));
            }
            set {
                this["AL_C601_SuKantariAsiriYukHatasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_C701_KatkiKantariAsiriYukHatasi {
            get {
                return ((bool)(this["AL_C701_KatkiKantariAsiriYukHatasi"]));
            }
            set {
                this["AL_C701_KatkiKantariAsiriYukHatasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A111_MikserDoluykenCalistirildi {
            get {
                return ((bool)(this["AL_A111_MikserDoluykenCalistirildi"]));
            }
            set {
                this["AL_A111_MikserDoluykenCalistirildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_FazHata1 {
            get {
                return ((bool)(this["AL_XB46_FazHata1"]));
            }
            set {
                this["AL_XB46_FazHata1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_FazHata2 {
            get {
                return ((bool)(this["AL_XB46_FazHata2"]));
            }
            set {
                this["AL_XB46_FazHata2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_FazHata3 {
            get {
                return ((bool)(this["AL_XB46_FazHata3"]));
            }
            set {
                this["AL_XB46_FazHata3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K404_SkipFrenBalatasiAsindiVeyaAyariBozulduVeyaFrenSwitchiAyariBozulduVeyaArizali {
            get {
                return ((bool)(this["AL_K404_SkipFrenBalatasiAsindiVeyaAyariBozulduVeyaFrenSwitchiAyariBozulduVeyaAriz" +
                    "ali"]));
            }
            set {
                this["AL_K404_SkipFrenBalatasiAsindiVeyaAyariBozulduVeyaFrenSwitchiAyariBozulduVeyaAriz" +
                    "ali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_GenelEmniyet {
            get {
                return ((bool)(this["AL_XB46_GenelEmniyet"]));
            }
            set {
                this["AL_XB46_GenelEmniyet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A400_SkipMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A400_SkipMotorTMSArizasi"]));
            }
            set {
                this["AL_A400_SkipMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K406_SkipAltPozisyonundaDegilVeyaPozisyonSwitchininAyariBozulduVeyaArizali {
            get {
                return ((bool)(this["AL_K406_SkipAltPozisyonundaDegilVeyaPozisyonSwitchininAyariBozulduVeyaArizali"]));
            }
            set {
                this["AL_K406_SkipAltPozisyonundaDegilVeyaPozisyonSwitchininAyariBozulduVeyaArizali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K105_MikserOtomatikYaglamaArizasiVeyaSwitchiArizali {
            get {
                return ((bool)(this["AL_K105_MikserOtomatikYaglamaArizasiVeyaSwitchiArizali"]));
            }
            set {
                this["AL_K105_MikserOtomatikYaglamaArizasiVeyaSwitchiArizali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A300_TransferKonveyorMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A300_TransferKonveyorMotorTMSArizasi"]));
            }
            set {
                this["AL_A300_TransferKonveyorMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_G801_BiriktirmeBunkerBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamadi {
            get {
                return ((bool)(this["AL_G801_BiriktirmeBunkerBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamad" +
                    "i"]));
            }
            set {
                this["AL_G801_BiriktirmeBunkerBosaltmaKapagiGirilenMaksimumSureIcindeAcilamadiKapanamad" +
                    "i"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_H510_CimentoKantarininAgirligiBosKabulEdilenMiktardanDahaFazla {
            get {
                return ((bool)(this["AL_H510_CimentoKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"]));
            }
            set {
                this["AL_H510_CimentoKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_H707_KatkiKantarininAgirligiBosKabulEdilenMiktardanDahaFazla {
            get {
                return ((bool)(this["AL_H707_KatkiKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"]));
            }
            set {
                this["AL_H707_KatkiKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_H607_SuKantarininAgirligiBosKabulEdilenMiktardanDahaFazla {
            get {
                return ((bool)(this["AL_H607_SuKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"]));
            }
            set {
                this["AL_H607_SuKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_H210_TartimKonveyoruKantarininAgirligiBosKabulEdilenMiktardanDahaFazla {
            get {
                return ((bool)(this["AL_H210_TartimKonveyoruKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"]));
            }
            set {
                this["AL_H210_TartimKonveyoruKantarininAgirligiBosKabulEdilenMiktardanDahaFazla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_D402_SkipMaksimunYurumeSuresiAsildi {
            get {
                return ((bool)(this["AL_D402_SkipMaksimunYurumeSuresiAsildi"]));
            }
            set {
                this["AL_D402_SkipMaksimunYurumeSuresiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_FrenKopruAriza {
            get {
                return ((bool)(this["AL_XB46_FrenKopruAriza"]));
            }
            set {
                this["AL_XB46_FrenKopruAriza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A500_CimentoHelezonMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A500_CimentoHelezonMotorTMSArizasi"]));
            }
            set {
                this["AL_A500_CimentoHelezonMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A700_KatkiPompaMotoruTMSArizasi {
            get {
                return ((bool)(this["AL_A700_KatkiPompaMotoruTMSArizasi"]));
            }
            set {
                this["AL_A700_KatkiPompaMotoruTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A600_SuKantariBosaltPompaMotorTMSArizasi {
            get {
                return ((bool)(this["AL_A600_SuKantariBosaltPompaMotorTMSArizasi"]));
            }
            set {
                this["AL_A600_SuKantariBosaltPompaMotorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K106_MikserMotoruAsiriIsindi70C_VeyaPTCTermistoruArizali {
            get {
                return ((bool)(this["AL_K106_MikserMotoruAsiriIsindi70C_VeyaPTCTermistoruArizali"]));
            }
            set {
                this["AL_K106_MikserMotoruAsiriIsindi70C_VeyaPTCTermistoruArizali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_L302_TransferKonveyorPullCordSwitchiCekildi {
            get {
                return ((bool)(this["AL_L302_TransferKonveyorPullCordSwitchiCekildi"]));
            }
            set {
                this["AL_L302_TransferKonveyorPullCordSwitchiCekildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_L208_TartiKonveyorPullCordSwitchiCekildi {
            get {
                return ((bool)(this["AL_L208_TartiKonveyorPullCordSwitchiCekildi"]));
            }
            set {
                this["AL_L208_TartiKonveyorPullCordSwitchiCekildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_HidrolikKapakHata {
            get {
                return ((bool)(this["AL_XB46_HidrolikKapakHata"]));
            }
            set {
                this["AL_XB46_HidrolikKapakHata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K108_MikserBakimKapagiAcildiVeyaSwitchiAyariBozulduVeyaArizali {
            get {
                return ((bool)(this["AL_K108_MikserBakimKapagiAcildiVeyaSwitchiAyariBozulduVeyaArizali"]));
            }
            set {
                this["AL_K108_MikserBakimKapagiAcildiVeyaSwitchiAyariBozulduVeyaArizali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B504_1_CimentoHelezon1MotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B504_1_CimentoHelezon1MotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B504_1_CimentoHelezon1MotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B504_2_CimentoHelezon2MotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B504_2_CimentoHelezon2MotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B504_2_CimentoHelezon2MotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B504_3_CimentoHelezon3MotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B504_3_CimentoHelezon3MotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B504_3_CimentoHelezon3MotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B504_4_CimentoHelezon4MotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B504_4_CimentoHelezon4MotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B504_4_CimentoHelezon4MotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B504_5_CimentoHelezon5MotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B504_5_CimentoHelezon5MotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B504_5_CimentoHelezon5MotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A202_2_AgregaBunker2VibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A202_2_AgregaBunker2VibratorTMSArizasi"]));
            }
            set {
                this["AL_A202_2_AgregaBunker2VibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A202_3_AgregaBunker3VibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A202_3_AgregaBunker3VibratorTMSArizasi"]));
            }
            set {
                this["AL_A202_3_AgregaBunker3VibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A501_CimentoKantarVibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A501_CimentoKantarVibratorTMSArizasi"]));
            }
            set {
                this["AL_A501_CimentoKantarVibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A201_1TartiKonveyor1VibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A201_1TartiKonveyor1VibratorTMSArizasi"]));
            }
            set {
                this["AL_A201_1TartiKonveyor1VibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A800_BiriktirmeBunkeriVibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A800_BiriktirmeBunkeriVibratorTMSArizasi"]));
            }
            set {
                this["AL_A800_BiriktirmeBunkeriVibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A201_2TartiKonveyor2VibratorTMSArizasi {
            get {
                return ((bool)(this["AL_A201_2TartiKonveyor2VibratorTMSArizasi"]));
            }
            set {
                this["AL_A201_2TartiKonveyor2VibratorTMSArizasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_K107_MikserReduktorYagiAsiriIsindi70VeyaSensorArizali {
            get {
                return ((bool)(this["AL_K107_MikserReduktorYagiAsiriIsindi70VeyaSensorArizali"]));
            }
            set {
                this["AL_K107_MikserReduktorYagiAsiriIsindi70VeyaSensorArizali"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_A112_MikserDurdu {
            get {
                return ((bool)(this["AL_A112_MikserDurdu"]));
            }
            set {
                this["AL_A112_MikserDurdu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_B103_MikserMotorAsiriAkimLimitiAsildi {
            get {
                return ((bool)(this["AL_B103_MikserMotorAsiriAkimLimitiAsildi"]));
            }
            set {
                this["AL_B103_MikserMotorAsiriAkimLimitiAsildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_E602_RecetedekiSuDegeriGirilenMaksimumSureIcindeKantaraAlinamadi {
            get {
                return ((bool)(this["AL_E602_RecetedekiSuDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"]));
            }
            set {
                this["AL_E602_RecetedekiSuDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_E702_RecetedekiKatkiDegeriGirilenMaksimumSureIcindeKantaraAlinamadi {
            get {
                return ((bool)(this["AL_E702_RecetedekiKatkiDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"]));
            }
            set {
                this["AL_E702_RecetedekiKatkiDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_E505_RecetedekiCimentoDegeriGirilenMaksimumSureIcindeKantaraAlinamadi {
            get {
                return ((bool)(this["AL_E505_RecetedekiCimentoDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"]));
            }
            set {
                this["AL_E505_RecetedekiCimentoDegeriGirilenMaksimumSureIcindeKantaraAlinamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_E205_RecetedekiAgregaDegeriGirilenMaksimumSureIcindeTartiKonveyoruneAlinamadi {
            get {
                return ((bool)(this["AL_E205_RecetedekiAgregaDegeriGirilenMaksimumSureIcindeTartiKonveyoruneAlinamadi"]));
            }
            set {
                this["AL_E205_RecetedekiAgregaDegeriGirilenMaksimumSureIcindeTartiKonveyoruneAlinamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_F506_CimentoKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi {
            get {
                return ((bool)(this["AL_F506_CimentoKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"]));
            }
            set {
                this["AL_F506_CimentoKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_F206_AgregaTartiKonveyoruGirilenMaksimumSureIcindeBosKabulEdilenmiktaraUlasamadi {
            get {
                return ((bool)(this["AL_F206_AgregaTartiKonveyoruGirilenMaksimumSureIcindeBosKabulEdilenmiktaraUlasama" +
                    "di"]));
            }
            set {
                this["AL_F206_AgregaTartiKonveyoruGirilenMaksimumSureIcindeBosKabulEdilenmiktaraUlasama" +
                    "di"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_F603_SuKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi {
            get {
                return ((bool)(this["AL_F603_SuKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"]));
            }
            set {
                this["AL_F603_SuKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_F703_KatkiKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi {
            get {
                return ((bool)(this["AL_F703_KatkiKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"]));
            }
            set {
                this["AL_F703_KatkiKantariGirilenMaksimumSureIcindeBosKabulEdilenMiktaraUlasamadi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AcilStopButonuBasildi {
            get {
                return ((bool)(this["AcilStopButonuBasildi"]));
            }
            set {
                this["AcilStopButonuBasildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_GenelHata {
            get {
                return ((bool)(this["AL_XB46_GenelHata"]));
            }
            set {
                this["AL_XB46_GenelHata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AL_XB46_FazHata {
            get {
                return ((bool)(this["AL_XB46_FazHata"]));
            }
            set {
                this["AL_XB46_FazHata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_158 {
            get {
                return ((bool)(this["Spare_158"]));
            }
            set {
                this["Spare_158"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_159 {
            get {
                return ((bool)(this["Spare_159"]));
            }
            set {
                this["Spare_159"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_160 {
            get {
                return ((bool)(this["Spare_160"]));
            }
            set {
                this["Spare_160"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_161 {
            get {
                return ((bool)(this["Spare_161"]));
            }
            set {
                this["Spare_161"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_162 {
            get {
                return ((bool)(this["Spare_162"]));
            }
            set {
                this["Spare_162"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_163 {
            get {
                return ((bool)(this["Spare_163"]));
            }
            set {
                this["Spare_163"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_164 {
            get {
                return ((bool)(this["Spare_164"]));
            }
            set {
                this["Spare_164"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_165 {
            get {
                return ((bool)(this["Spare_165"]));
            }
            set {
                this["Spare_165"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_166 {
            get {
                return ((bool)(this["Spare_166"]));
            }
            set {
                this["Spare_166"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_167 {
            get {
                return ((bool)(this["Spare_167"]));
            }
            set {
                this["Spare_167"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_168 {
            get {
                return ((bool)(this["Spare_168"]));
            }
            set {
                this["Spare_168"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_169 {
            get {
                return ((bool)(this["Spare_169"]));
            }
            set {
                this["Spare_169"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_170 {
            get {
                return ((bool)(this["Spare_170"]));
            }
            set {
                this["Spare_170"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_171 {
            get {
                return ((bool)(this["Spare_171"]));
            }
            set {
                this["Spare_171"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_172 {
            get {
                return ((bool)(this["Spare_172"]));
            }
            set {
                this["Spare_172"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_173 {
            get {
                return ((bool)(this["Spare_173"]));
            }
            set {
                this["Spare_173"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_174 {
            get {
                return ((bool)(this["Spare_174"]));
            }
            set {
                this["Spare_174"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_175 {
            get {
                return ((bool)(this["Spare_175"]));
            }
            set {
                this["Spare_175"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_176 {
            get {
                return ((bool)(this["Spare_176"]));
            }
            set {
                this["Spare_176"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_177 {
            get {
                return ((bool)(this["Spare_177"]));
            }
            set {
                this["Spare_177"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_178 {
            get {
                return ((bool)(this["Spare_178"]));
            }
            set {
                this["Spare_178"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_179 {
            get {
                return ((bool)(this["Spare_179"]));
            }
            set {
                this["Spare_179"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_180 {
            get {
                return ((bool)(this["Spare_180"]));
            }
            set {
                this["Spare_180"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_181 {
            get {
                return ((bool)(this["Spare_181"]));
            }
            set {
                this["Spare_181"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_182 {
            get {
                return ((bool)(this["Spare_182"]));
            }
            set {
                this["Spare_182"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_183 {
            get {
                return ((bool)(this["Spare_183"]));
            }
            set {
                this["Spare_183"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_184 {
            get {
                return ((bool)(this["Spare_184"]));
            }
            set {
                this["Spare_184"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_185 {
            get {
                return ((bool)(this["Spare_185"]));
            }
            set {
                this["Spare_185"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_186 {
            get {
                return ((bool)(this["Spare_186"]));
            }
            set {
                this["Spare_186"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_187 {
            get {
                return ((bool)(this["Spare_187"]));
            }
            set {
                this["Spare_187"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_188 {
            get {
                return ((bool)(this["Spare_188"]));
            }
            set {
                this["Spare_188"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_189 {
            get {
                return ((bool)(this["Spare_189"]));
            }
            set {
                this["Spare_189"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_190 {
            get {
                return ((bool)(this["Spare_190"]));
            }
            set {
                this["Spare_190"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_191 {
            get {
                return ((bool)(this["Spare_191"]));
            }
            set {
                this["Spare_191"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_192 {
            get {
                return ((bool)(this["Spare_192"]));
            }
            set {
                this["Spare_192"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_193 {
            get {
                return ((bool)(this["Spare_193"]));
            }
            set {
                this["Spare_193"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_194 {
            get {
                return ((bool)(this["Spare_194"]));
            }
            set {
                this["Spare_194"] = value;
            }
        }
    }
}
