//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M011_ButonLar : global::System.Configuration.ApplicationSettingsBase {
        
        private static M011_ButonLar defaultInstance = ((M011_ButonLar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M011_ButonLar())));
        
        public static M011_ButonLar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega1 {
            get {
                return ((bool)(this["is_ButonAgrega1"]));
            }
            set {
                this["is_ButonAgrega1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega2 {
            get {
                return ((bool)(this["is_ButonAgrega2"]));
            }
            set {
                this["is_ButonAgrega2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega3 {
            get {
                return ((bool)(this["is_ButonAgrega3"]));
            }
            set {
                this["is_ButonAgrega3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega4 {
            get {
                return ((bool)(this["is_ButonAgrega4"]));
            }
            set {
                this["is_ButonAgrega4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega5 {
            get {
                return ((bool)(this["is_ButonAgrega5"]));
            }
            set {
                this["is_ButonAgrega5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega6 {
            get {
                return ((bool)(this["is_ButonAgrega6"]));
            }
            set {
                this["is_ButonAgrega6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega7 {
            get {
                return ((bool)(this["is_ButonAgrega7"]));
            }
            set {
                this["is_ButonAgrega7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega8 {
            get {
                return ((bool)(this["is_ButonAgrega8"]));
            }
            set {
                this["is_ButonAgrega8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento1 {
            get {
                return ((bool)(this["is_ButonCimento1"]));
            }
            set {
                this["is_ButonCimento1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento2 {
            get {
                return ((bool)(this["is_ButonCimento2"]));
            }
            set {
                this["is_ButonCimento2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento3 {
            get {
                return ((bool)(this["is_ButonCimento3"]));
            }
            set {
                this["is_ButonCimento3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento4 {
            get {
                return ((bool)(this["is_ButonCimento4"]));
            }
            set {
                this["is_ButonCimento4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento5 {
            get {
                return ((bool)(this["is_ButonCimento5"]));
            }
            set {
                this["is_ButonCimento5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimento6 {
            get {
                return ((bool)(this["is_ButonCimento6"]));
            }
            set {
                this["is_ButonCimento6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki1 {
            get {
                return ((bool)(this["is_ButonKatki1"]));
            }
            set {
                this["is_ButonKatki1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki2 {
            get {
                return ((bool)(this["is_ButonKatki2"]));
            }
            set {
                this["is_ButonKatki2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki3 {
            get {
                return ((bool)(this["is_ButonKatki3"]));
            }
            set {
                this["is_ButonKatki3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki4 {
            get {
                return ((bool)(this["is_ButonKatki4"]));
            }
            set {
                this["is_ButonKatki4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki5 {
            get {
                return ((bool)(this["is_ButonKatki5"]));
            }
            set {
                this["is_ButonKatki5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatki6 {
            get {
                return ((bool)(this["is_ButonKatki6"]));
            }
            set {
                this["is_ButonKatki6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSu1 {
            get {
                return ((bool)(this["is_ButonSu1"]));
            }
            set {
                this["is_ButonSu1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSu2 {
            get {
                return ((bool)(this["is_ButonSu2"]));
            }
            set {
                this["is_ButonSu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSu3 {
            get {
                return ((bool)(this["is_ButonSu3"]));
            }
            set {
                this["is_ButonSu3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSu4 {
            get {
                return ((bool)(this["is_ButonSu4"]));
            }
            set {
                this["is_ButonSu4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonHassasAgrega {
            get {
                return ((bool)(this["is_ButonHassasAgrega"]));
            }
            set {
                this["is_ButonHassasAgrega"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonVibBesAg1 {
            get {
                return ((bool)(this["is_ButonVibBesAg1"]));
            }
            set {
                this["is_ButonVibBesAg1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimentoBosalt {
            get {
                return ((bool)(this["is_ButonCimentoBosalt"]));
            }
            set {
                this["is_ButonCimentoBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatkiBosalt {
            get {
                return ((bool)(this["is_ButonKatkiBosalt"]));
            }
            set {
                this["is_ButonKatkiBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSuBosalt {
            get {
                return ((bool)(this["is_ButonSuBosalt"]));
            }
            set {
                this["is_ButonSuBosalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKatkiYikama {
            get {
                return ((bool)(this["is_ButonKatkiYikama"]));
            }
            set {
                this["is_ButonKatkiYikama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonMikserStop {
            get {
                return ((bool)(this["is_ButonMikserStop"]));
            }
            set {
                this["is_ButonMikserStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonMikserStart {
            get {
                return ((bool)(this["is_ButonMikserStart"]));
            }
            set {
                this["is_ButonMikserStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonMikserKapakAc {
            get {
                return ((bool)(this["is_ButonMikserKapakAc"]));
            }
            set {
                this["is_ButonMikserKapakAc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonMikserKapakKapak {
            get {
                return ((bool)(this["is_ButonMikserKapakKapak"]));
            }
            set {
                this["is_ButonMikserKapakKapak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre1 {
            get {
                return ((bool)(this["is_ButonFiltre1"]));
            }
            set {
                this["is_ButonFiltre1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre2 {
            get {
                return ((bool)(this["is_ButonFiltre2"]));
            }
            set {
                this["is_ButonFiltre2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre3 {
            get {
                return ((bool)(this["is_ButonFiltre3"]));
            }
            set {
                this["is_ButonFiltre3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre4 {
            get {
                return ((bool)(this["is_ButonFiltre4"]));
            }
            set {
                this["is_ButonFiltre4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre5 {
            get {
                return ((bool)(this["is_ButonFiltre5"]));
            }
            set {
                this["is_ButonFiltre5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonFiltre6 {
            get {
                return ((bool)(this["is_ButonFiltre6"]));
            }
            set {
                this["is_ButonFiltre6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKovaYukari {
            get {
                return ((bool)(this["is_ButonKovaYukari"]));
            }
            set {
                this["is_ButonKovaYukari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKovaAsagi {
            get {
                return ((bool)(this["is_ButonKovaAsagi"]));
            }
            set {
                this["is_ButonKovaAsagi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_TransferBandButon {
            get {
                return ((bool)(this["is_TransferBandButon"]));
            }
            set {
                this["is_TransferBandButon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonTartiBand1 {
            get {
                return ((bool)(this["is_ButonTartiBand1"]));
            }
            set {
                this["is_ButonTartiBand1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonTartiBand1Vibrator {
            get {
                return ((bool)(this["is_ButonTartiBand1Vibrator"]));
            }
            set {
                this["is_ButonTartiBand1Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega1Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega1Vibrator"]));
            }
            set {
                this["is_ButonAgrega1Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega2Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega2Vibrator"]));
            }
            set {
                this["is_ButonAgrega2Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega3Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega3Vibrator"]));
            }
            set {
                this["is_ButonAgrega3Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega4Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega4Vibrator"]));
            }
            set {
                this["is_ButonAgrega4Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega5Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega5Vibrator"]));
            }
            set {
                this["is_ButonAgrega5Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega6Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega6Vibrator"]));
            }
            set {
                this["is_ButonAgrega6Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega7Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega7Vibrator"]));
            }
            set {
                this["is_ButonAgrega7Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonAgrega8Vibrator {
            get {
                return ((bool)(this["is_ButonAgrega8Vibrator"]));
            }
            set {
                this["is_ButonAgrega8Vibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonSoklama {
            get {
                return ((bool)(this["is_ButonSoklama"]));
            }
            set {
                this["is_ButonSoklama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKompresor {
            get {
                return ((bool)(this["is_ButonKompresor"]));
            }
            set {
                this["is_ButonKompresor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonKorna {
            get {
                return ((bool)(this["is_ButonKorna"]));
            }
            set {
                this["is_ButonKorna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonMikserBlokFiltre {
            get {
                return ((bool)(this["is_ButonMikserBlokFiltre"]));
            }
            set {
                this["is_ButonMikserBlokFiltre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonCimentoBosaltVibrator {
            get {
                return ((bool)(this["is_ButonCimentoBosaltVibrator"]));
            }
            set {
                this["is_ButonCimentoBosaltVibrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_195 {
            get {
                return ((bool)(this["Spare_195"]));
            }
            set {
                this["Spare_195"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_196 {
            get {
                return ((bool)(this["Spare_196"]));
            }
            set {
                this["Spare_196"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_197 {
            get {
                return ((bool)(this["Spare_197"]));
            }
            set {
                this["Spare_197"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_198 {
            get {
                return ((bool)(this["Spare_198"]));
            }
            set {
                this["Spare_198"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_199 {
            get {
                return ((bool)(this["Spare_199"]));
            }
            set {
                this["Spare_199"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_200 {
            get {
                return ((bool)(this["Spare_200"]));
            }
            set {
                this["Spare_200"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_201 {
            get {
                return ((bool)(this["Spare_201"]));
            }
            set {
                this["Spare_201"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_202 {
            get {
                return ((bool)(this["Spare_202"]));
            }
            set {
                this["Spare_202"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_203 {
            get {
                return ((bool)(this["Spare_203"]));
            }
            set {
                this["Spare_203"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_204 {
            get {
                return ((bool)(this["Spare_204"]));
            }
            set {
                this["Spare_204"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_205 {
            get {
                return ((bool)(this["Spare_205"]));
            }
            set {
                this["Spare_205"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_206 {
            get {
                return ((bool)(this["Spare_206"]));
            }
            set {
                this["Spare_206"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_207 {
            get {
                return ((bool)(this["Spare_207"]));
            }
            set {
                this["Spare_207"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_208 {
            get {
                return ((bool)(this["Spare_208"]));
            }
            set {
                this["Spare_208"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_209 {
            get {
                return ((bool)(this["Spare_209"]));
            }
            set {
                this["Spare_209"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_210 {
            get {
                return ((bool)(this["Spare_210"]));
            }
            set {
                this["Spare_210"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_211 {
            get {
                return ((bool)(this["Spare_211"]));
            }
            set {
                this["Spare_211"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_212 {
            get {
                return ((bool)(this["Spare_212"]));
            }
            set {
                this["Spare_212"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_213 {
            get {
                return ((bool)(this["Spare_213"]));
            }
            set {
                this["Spare_213"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_214 {
            get {
                return ((bool)(this["Spare_214"]));
            }
            set {
                this["Spare_214"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_215 {
            get {
                return ((bool)(this["Spare_215"]));
            }
            set {
                this["Spare_215"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_216 {
            get {
                return ((bool)(this["Spare_216"]));
            }
            set {
                this["Spare_216"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_217 {
            get {
                return ((bool)(this["Spare_217"]));
            }
            set {
                this["Spare_217"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_218 {
            get {
                return ((bool)(this["Spare_218"]));
            }
            set {
                this["Spare_218"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_219 {
            get {
                return ((bool)(this["Spare_219"]));
            }
            set {
                this["Spare_219"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_220 {
            get {
                return ((bool)(this["Spare_220"]));
            }
            set {
                this["Spare_220"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_221 {
            get {
                return ((bool)(this["Spare_221"]));
            }
            set {
                this["Spare_221"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_222 {
            get {
                return ((bool)(this["Spare_222"]));
            }
            set {
                this["Spare_222"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_223 {
            get {
                return ((bool)(this["Spare_223"]));
            }
            set {
                this["Spare_223"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_224 {
            get {
                return ((bool)(this["Spare_224"]));
            }
            set {
                this["Spare_224"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_225 {
            get {
                return ((bool)(this["Spare_225"]));
            }
            set {
                this["Spare_225"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_226 {
            get {
                return ((bool)(this["Spare_226"]));
            }
            set {
                this["Spare_226"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_227 {
            get {
                return ((bool)(this["Spare_227"]));
            }
            set {
                this["Spare_227"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_228 {
            get {
                return ((bool)(this["Spare_228"]));
            }
            set {
                this["Spare_228"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_229 {
            get {
                return ((bool)(this["Spare_229"]));
            }
            set {
                this["Spare_229"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_230 {
            get {
                return ((bool)(this["Spare_230"]));
            }
            set {
                this["Spare_230"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_231 {
            get {
                return ((bool)(this["Spare_231"]));
            }
            set {
                this["Spare_231"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_232 {
            get {
                return ((bool)(this["Spare_232"]));
            }
            set {
                this["Spare_232"] = value;
            }
        }
    }
}
