//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M012_Lambalar : global::System.Configuration.ApplicationSettingsBase {
        
        private static M012_Lambalar defaultInstance = ((M012_Lambalar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M012_Lambalar())));
        
        public static M012_Lambalar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega1Lambasi {
            get {
                return ((bool)(this["qs_Agrega1Lambasi"]));
            }
            set {
                this["qs_Agrega1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega2Lambasi {
            get {
                return ((bool)(this["qs_Agrega2Lambasi"]));
            }
            set {
                this["qs_Agrega2Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega3Lambasi {
            get {
                return ((bool)(this["qs_Agrega3Lambasi"]));
            }
            set {
                this["qs_Agrega3Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega4Lambasi {
            get {
                return ((bool)(this["qs_Agrega4Lambasi"]));
            }
            set {
                this["qs_Agrega4Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega5Lambasi {
            get {
                return ((bool)(this["qs_Agrega5Lambasi"]));
            }
            set {
                this["qs_Agrega5Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega6Lambasi {
            get {
                return ((bool)(this["qs_Agrega6Lambasi"]));
            }
            set {
                this["qs_Agrega6Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento1Lambasi {
            get {
                return ((bool)(this["qs_Cimento1Lambasi"]));
            }
            set {
                this["qs_Cimento1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento2Lambasi {
            get {
                return ((bool)(this["qs_Cimento2Lambasi"]));
            }
            set {
                this["qs_Cimento2Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento3Lambasi {
            get {
                return ((bool)(this["qs_Cimento3Lambasi"]));
            }
            set {
                this["qs_Cimento3Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento4Lambasi {
            get {
                return ((bool)(this["qs_Cimento4Lambasi"]));
            }
            set {
                this["qs_Cimento4Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento5Lambasi {
            get {
                return ((bool)(this["qs_Cimento5Lambasi"]));
            }
            set {
                this["qs_Cimento5Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Cimento6Lambasi {
            get {
                return ((bool)(this["qs_Cimento6Lambasi"]));
            }
            set {
                this["qs_Cimento6Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki1Lambasi {
            get {
                return ((bool)(this["qs_Katki1Lambasi"]));
            }
            set {
                this["qs_Katki1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki2Lambasi {
            get {
                return ((bool)(this["qs_Katki2Lambasi"]));
            }
            set {
                this["qs_Katki2Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki3Lambasi {
            get {
                return ((bool)(this["qs_Katki3Lambasi"]));
            }
            set {
                this["qs_Katki3Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki4Lambasi {
            get {
                return ((bool)(this["qs_Katki4Lambasi"]));
            }
            set {
                this["qs_Katki4Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki5Lambasi {
            get {
                return ((bool)(this["qs_Katki5Lambasi"]));
            }
            set {
                this["qs_Katki5Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Katki6Lambasi {
            get {
                return ((bool)(this["qs_Katki6Lambasi"]));
            }
            set {
                this["qs_Katki6Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Su1Lambasi {
            get {
                return ((bool)(this["qs_Su1Lambasi"]));
            }
            set {
                this["qs_Su1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Su2Lambasi {
            get {
                return ((bool)(this["qs_Su2Lambasi"]));
            }
            set {
                this["qs_Su2Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Su3Lambasi {
            get {
                return ((bool)(this["qs_Su3Lambasi"]));
            }
            set {
                this["qs_Su3Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Su4Lambasi {
            get {
                return ((bool)(this["qs_Su4Lambasi"]));
            }
            set {
                this["qs_Su4Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_LambaHassasAgrega {
            get {
                return ((bool)(this["qs_LambaHassasAgrega"]));
            }
            set {
                this["qs_LambaHassasAgrega"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega1VibBesLambasi {
            get {
                return ((bool)(this["qs_Agrega1VibBesLambasi"]));
            }
            set {
                this["qs_Agrega1VibBesLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_CimentoBosaltLambasi {
            get {
                return ((bool)(this["qs_CimentoBosaltLambasi"]));
            }
            set {
                this["qs_CimentoBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_CimentoBosaltVibratorLambasi {
            get {
                return ((bool)(this["qs_CimentoBosaltVibratorLambasi"]));
            }
            set {
                this["qs_CimentoBosaltVibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KatkiBosaltLambasi {
            get {
                return ((bool)(this["qs_KatkiBosaltLambasi"]));
            }
            set {
                this["qs_KatkiBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_SuBosaltLambasi {
            get {
                return ((bool)(this["qs_SuBosaltLambasi"]));
            }
            set {
                this["qs_SuBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_MikserStartLambasi {
            get {
                return ((bool)(this["qs_MikserStartLambasi"]));
            }
            set {
                this["qs_MikserStartLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_MikserKapakAcikLambasi {
            get {
                return ((bool)(this["qs_MikserKapakAcikLambasi"]));
            }
            set {
                this["qs_MikserKapakAcikLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_MikserKapakKapaliLambasi {
            get {
                return ((bool)(this["qs_MikserKapakKapaliLambasi"]));
            }
            set {
                this["qs_MikserKapakKapaliLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_MikserArizaLambasi {
            get {
                return ((bool)(this["qs_MikserArizaLambasi"]));
            }
            set {
                this["qs_MikserArizaLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre1Lambasi {
            get {
                return ((bool)(this["qs_Filtre1Lambasi"]));
            }
            set {
                this["qs_Filtre1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre2Lambasi {
            get {
                return ((bool)(this["qs_Filtre2Lambasi"]));
            }
            set {
                this["qs_Filtre2Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre3Lambasi {
            get {
                return ((bool)(this["qs_Filtre3Lambasi"]));
            }
            set {
                this["qs_Filtre3Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre4Lambasi {
            get {
                return ((bool)(this["qs_Filtre4Lambasi"]));
            }
            set {
                this["qs_Filtre4Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre5Lambasi {
            get {
                return ((bool)(this["qs_Filtre5Lambasi"]));
            }
            set {
                this["qs_Filtre5Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Filtre6Lambasi {
            get {
                return ((bool)(this["qs_Filtre6Lambasi"]));
            }
            set {
                this["qs_Filtre6Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KovaAsagidaLambasi {
            get {
                return ((bool)(this["qs_KovaAsagidaLambasi"]));
            }
            set {
                this["qs_KovaAsagidaLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KovaYukaridaLambasi {
            get {
                return ((bool)(this["qs_KovaYukaridaLambasi"]));
            }
            set {
                this["qs_KovaYukaridaLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KovaOrtadaLambasi {
            get {
                return ((bool)(this["qs_KovaOrtadaLambasi"]));
            }
            set {
                this["qs_KovaOrtadaLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KovaYukariLambasi {
            get {
                return ((bool)(this["qs_KovaYukariLambasi"]));
            }
            set {
                this["qs_KovaYukariLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KovaAsagiLambasi {
            get {
                return ((bool)(this["qs_KovaAsagiLambasi"]));
            }
            set {
                this["qs_KovaAsagiLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_FrenAcik {
            get {
                return ((bool)(this["qs_FrenAcik"]));
            }
            set {
                this["qs_FrenAcik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_TransferBandLamba {
            get {
                return ((bool)(this["qs_TransferBandLamba"]));
            }
            set {
                this["qs_TransferBandLamba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_TartiBand1Lambasi {
            get {
                return ((bool)(this["qs_TartiBand1Lambasi"]));
            }
            set {
                this["qs_TartiBand1Lambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_TartiBand1VibratorLambasi {
            get {
                return ((bool)(this["qs_TartiBand1VibratorLambasi"]));
            }
            set {
                this["qs_TartiBand1VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega1VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega1VibratorLambasi"]));
            }
            set {
                this["qs_Agrega1VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega2VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega2VibratorLambasi"]));
            }
            set {
                this["qs_Agrega2VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega3VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega3VibratorLambasi"]));
            }
            set {
                this["qs_Agrega3VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega4VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega4VibratorLambasi"]));
            }
            set {
                this["qs_Agrega4VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega5VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega5VibratorLambasi"]));
            }
            set {
                this["qs_Agrega5VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_Agrega6VibratorLambasi {
            get {
                return ((bool)(this["qs_Agrega6VibratorLambasi"]));
            }
            set {
                this["qs_Agrega6VibratorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_SoklamaLambasi {
            get {
                return ((bool)(this["qs_SoklamaLambasi"]));
            }
            set {
                this["qs_SoklamaLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_KompresorLambasi {
            get {
                return ((bool)(this["qs_KompresorLambasi"]));
            }
            set {
                this["qs_KompresorLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_MikserBlokFiltreLambasi {
            get {
                return ((bool)(this["qs_MikserBlokFiltreLambasi"]));
            }
            set {
                this["qs_MikserBlokFiltreLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_OtomatikStartLambasi {
            get {
                return ((bool)(this["qs_OtomatikStartLambasi"]));
            }
            set {
                this["qs_OtomatikStartLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_YrdButonMikserAcLambasi {
            get {
                return ((bool)(this["qs_YrdButonMikserAcLambasi"]));
            }
            set {
                this["qs_YrdButonMikserAcLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_YrdButonCimentoBosaltLambasi {
            get {
                return ((bool)(this["qs_YrdButonCimentoBosaltLambasi"]));
            }
            set {
                this["qs_YrdButonCimentoBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_YrdButonKatkiBosaltLambasi {
            get {
                return ((bool)(this["qs_YrdButonKatkiBosaltLambasi"]));
            }
            set {
                this["qs_YrdButonKatkiBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qs_YrdButonSuBosaltLambasi {
            get {
                return ((bool)(this["qs_YrdButonSuBosaltLambasi"]));
            }
            set {
                this["qs_YrdButonSuBosaltLambasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_AcilStop {
            get {
                return ((bool)(this["is_AcilStop"]));
            }
            set {
                this["is_AcilStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonManualde {
            get {
                return ((bool)(this["is_ButonManualde"]));
            }
            set {
                this["is_ButonManualde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonOtomatikte {
            get {
                return ((bool)(this["is_ButonOtomatikte"]));
            }
            set {
                this["is_ButonOtomatikte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_ModYariOtomatik {
            get {
                return ((bool)(this["s_ModYariOtomatik"]));
            }
            set {
                this["s_ModYariOtomatik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonStart {
            get {
                return ((bool)(this["is_ButonStart"]));
            }
            set {
                this["is_ButonStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool is_ButonStop {
            get {
                return ((bool)(this["is_ButonStop"]));
            }
            set {
                this["is_ButonStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_233 {
            get {
                return ((bool)(this["Spare_233"]));
            }
            set {
                this["Spare_233"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_234 {
            get {
                return ((bool)(this["Spare_234"]));
            }
            set {
                this["Spare_234"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_235 {
            get {
                return ((bool)(this["Spare_235"]));
            }
            set {
                this["Spare_235"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_236 {
            get {
                return ((bool)(this["Spare_236"]));
            }
            set {
                this["Spare_236"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_237 {
            get {
                return ((bool)(this["Spare_237"]));
            }
            set {
                this["Spare_237"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_238 {
            get {
                return ((bool)(this["Spare_238"]));
            }
            set {
                this["Spare_238"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_239 {
            get {
                return ((bool)(this["Spare_239"]));
            }
            set {
                this["Spare_239"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_240 {
            get {
                return ((bool)(this["Spare_240"]));
            }
            set {
                this["Spare_240"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_241 {
            get {
                return ((bool)(this["Spare_241"]));
            }
            set {
                this["Spare_241"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_242 {
            get {
                return ((bool)(this["Spare_242"]));
            }
            set {
                this["Spare_242"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_243 {
            get {
                return ((bool)(this["Spare_243"]));
            }
            set {
                this["Spare_243"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_244 {
            get {
                return ((bool)(this["Spare_244"]));
            }
            set {
                this["Spare_244"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_245 {
            get {
                return ((bool)(this["Spare_245"]));
            }
            set {
                this["Spare_245"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_246 {
            get {
                return ((bool)(this["Spare_246"]));
            }
            set {
                this["Spare_246"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_247 {
            get {
                return ((bool)(this["Spare_247"]));
            }
            set {
                this["Spare_247"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_248 {
            get {
                return ((bool)(this["Spare_248"]));
            }
            set {
                this["Spare_248"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_249 {
            get {
                return ((bool)(this["Spare_249"]));
            }
            set {
                this["Spare_249"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_250 {
            get {
                return ((bool)(this["Spare_250"]));
            }
            set {
                this["Spare_250"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_251 {
            get {
                return ((bool)(this["Spare_251"]));
            }
            set {
                this["Spare_251"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_252 {
            get {
                return ((bool)(this["Spare_252"]));
            }
            set {
                this["Spare_252"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_253 {
            get {
                return ((bool)(this["Spare_253"]));
            }
            set {
                this["Spare_253"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_254 {
            get {
                return ((bool)(this["Spare_254"]));
            }
            set {
                this["Spare_254"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_255 {
            get {
                return ((bool)(this["Spare_255"]));
            }
            set {
                this["Spare_255"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_256 {
            get {
                return ((bool)(this["Spare_256"]));
            }
            set {
                this["Spare_256"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_257 {
            get {
                return ((bool)(this["Spare_257"]));
            }
            set {
                this["Spare_257"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_258 {
            get {
                return ((bool)(this["Spare_258"]));
            }
            set {
                this["Spare_258"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_259 {
            get {
                return ((bool)(this["Spare_259"]));
            }
            set {
                this["Spare_259"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_260 {
            get {
                return ((bool)(this["Spare_260"]));
            }
            set {
                this["Spare_260"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Spare_261 {
            get {
                return ((bool)(this["Spare_261"]));
            }
            set {
                this["Spare_261"] = value;
            }
        }
    }
}
