//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M014_Genel : global::System.Configuration.ApplicationSettingsBase {
        
        private static M014_Genel defaultInstance = ((M014_Genel)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M014_Genel())));
        
        public static M014_Genel Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string v_Ag1VibratorluBeslemeBolgesinde {
            get {
                return ((string)(this["v_Ag1VibratorluBeslemeBolgesinde"]));
            }
            set {
                this["v_Ag1VibratorluBeslemeBolgesinde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string v_Ag2VibratorluBeslemeBolgesinde {
            get {
                return ((string)(this["v_Ag2VibratorluBeslemeBolgesinde"]));
            }
            set {
                this["v_Ag2VibratorluBeslemeBolgesinde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string v_Ag3VibratorluBeslemeBolgesinde {
            get {
                return ((string)(this["v_Ag3VibratorluBeslemeBolgesinde"]));
            }
            set {
                this["v_Ag3VibratorluBeslemeBolgesinde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string v_Ag4VibratorluBeslemeBolgesinde {
            get {
                return ((string)(this["v_Ag4VibratorluBeslemeBolgesinde"]));
            }
            set {
                this["v_Ag4VibratorluBeslemeBolgesinde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string v_ArizaLambaPulse {
            get {
                return ((string)(this["v_ArizaLambaPulse"]));
            }
            set {
                this["v_ArizaLambaPulse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Saniye {
            get {
                return ((string)(this["Saniye"]));
            }
            set {
                this["Saniye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataChange {
            get {
                return ((string)(this["DataChange"]));
            }
            set {
                this["DataChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB250_OzelIptal {
            get {
                return ((string)(this["DB250_OzelIptal"]));
            }
            set {
                this["DB250_OzelIptal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_ZamanSenkronizasyonuSaglandi {
            get {
                return ((string)(this["s_ZamanSenkronizasyonuSaglandi"]));
            }
            set {
                this["s_ZamanSenkronizasyonuSaglandi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Hour {
            get {
                return ((byte)(this["PLC_Hour"]));
            }
            set {
                this["PLC_Hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Min {
            get {
                return ((byte)(this["PLC_Min"]));
            }
            set {
                this["PLC_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Sec {
            get {
                return ((byte)(this["PLC_Sec"]));
            }
            set {
                this["PLC_Sec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Month {
            get {
                return ((byte)(this["PLC_Month"]));
            }
            set {
                this["PLC_Month"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Day {
            get {
                return ((byte)(this["PLC_Day"]));
            }
            set {
                this["PLC_Day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Wday {
            get {
                return ((byte)(this["PLC_Wday"]));
            }
            set {
                this["PLC_Wday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PLC_Old_Day {
            get {
                return ((byte)(this["PLC_Old_Day"]));
            }
            set {
                this["PLC_Old_Day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLC_Year {
            get {
                return ((int)(this["PLC_Year"]));
            }
            set {
                this["PLC_Year"] = value;
            }
        }
    }
}
