//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M015_Agrega : global::System.Configuration.ApplicationSettingsBase {
        
        private static M015_Agrega defaultInstance = ((M015_Agrega)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M015_Agrega())));
        
        public static M015_Agrega Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_AgregaKantar {
            get {
                return ((int)(this["XB2_AgregaKantar"]));
            }
            set {
                this["XB2_AgregaKantar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_AraKantarAgrega {
            get {
                return ((int)(this["XB19_AraKantarAgrega"]));
            }
            set {
                this["XB19_AraKantarAgrega"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag1Su {
            get {
                return ((int)(this["XB2_Ag1Su"]));
            }
            set {
                this["XB2_Ag1Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag2Su {
            get {
                return ((int)(this["XB2_Ag2Su"]));
            }
            set {
                this["XB2_Ag2Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag3Su {
            get {
                return ((int)(this["XB2_Ag3Su"]));
            }
            set {
                this["XB2_Ag3Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag4Su {
            get {
                return ((int)(this["XB2_Ag4Su"]));
            }
            set {
                this["XB2_Ag4Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag5Su {
            get {
                return ((int)(this["XB2_Ag5Su"]));
            }
            set {
                this["XB2_Ag5Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag6Su {
            get {
                return ((int)(this["XB2_Ag6Su"]));
            }
            set {
                this["XB2_Ag6Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag7Su {
            get {
                return ((int)(this["XB2_Ag7Su"]));
            }
            set {
                this["XB2_Ag7Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag8Su {
            get {
                return ((int)(this["XB2_Ag8Su"]));
            }
            set {
                this["XB2_Ag8Su"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB2_Ag1MalAlim {
            get {
                return ((int)(this["XB2_Ag1MalAlim"]));
            }
            set {
                this["XB2_Ag1MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag2MalAlim {
            get {
                return ((long)(this["XB2_Ag2MalAlim"]));
            }
            set {
                this["XB2_Ag2MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag3MalAlim {
            get {
                return ((long)(this["XB2_Ag3MalAlim"]));
            }
            set {
                this["XB2_Ag3MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag4MalAlim {
            get {
                return ((long)(this["XB2_Ag4MalAlim"]));
            }
            set {
                this["XB2_Ag4MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag5MalAlim {
            get {
                return ((long)(this["XB2_Ag5MalAlim"]));
            }
            set {
                this["XB2_Ag5MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag6MalAlim {
            get {
                return ((long)(this["XB2_Ag6MalAlim"]));
            }
            set {
                this["XB2_Ag6MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag7MalAlim {
            get {
                return ((long)(this["XB2_Ag7MalAlim"]));
            }
            set {
                this["XB2_Ag7MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long XB2_Ag8MalAlim {
            get {
                return ((long)(this["XB2_Ag8MalAlim"]));
            }
            set {
                this["XB2_Ag8MalAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega1Nem {
            get {
                return ((double)(this["XB19_Agrega1Nem"]));
            }
            set {
                this["XB19_Agrega1Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega2Nem {
            get {
                return ((double)(this["XB19_Agrega2Nem"]));
            }
            set {
                this["XB19_Agrega2Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega3Nem {
            get {
                return ((double)(this["XB19_Agrega3Nem"]));
            }
            set {
                this["XB19_Agrega3Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega4Nem {
            get {
                return ((double)(this["XB19_Agrega4Nem"]));
            }
            set {
                this["XB19_Agrega4Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega5Nem {
            get {
                return ((double)(this["XB19_Agrega5Nem"]));
            }
            set {
                this["XB19_Agrega5Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega6Nem {
            get {
                return ((double)(this["XB19_Agrega6Nem"]));
            }
            set {
                this["XB19_Agrega6Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega7Nem {
            get {
                return ((double)(this["XB19_Agrega7Nem"]));
            }
            set {
                this["XB19_Agrega7Nem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Agrega8Nem {
            get {
                return ((double)(this["XB19_Agrega8Nem"]));
            }
            set {
                this["XB19_Agrega8Nem"] = value;
            }
        }
    }
}
