//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M016_Cimento : global::System.Configuration.ApplicationSettingsBase {
        
        private static M016_Cimento defaultInstance = ((M016_Cimento)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M016_Cimento())));
        
        public static M016_Cimento Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CMKantar {
            get {
                return ((int)(this["XB3_CMKantar"]));
            }
            set {
                this["XB3_CMKantar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_AraKantarCimento {
            get {
                return ((int)(this["XB19_AraKantarCimento"]));
            }
            set {
                this["XB19_AraKantarCimento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM1ManAlim {
            get {
                return ((int)(this["XB3_CM1ManAlim"]));
            }
            set {
                this["XB3_CM1ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM2ManAlim {
            get {
                return ((int)(this["XB3_CM2ManAlim"]));
            }
            set {
                this["XB3_CM2ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM3ManAlim {
            get {
                return ((int)(this["XB3_CM3ManAlim"]));
            }
            set {
                this["XB3_CM3ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM4ManAlim {
            get {
                return ((int)(this["XB3_CM4ManAlim"]));
            }
            set {
                this["XB3_CM4ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM5ManAlim {
            get {
                return ((int)(this["XB3_CM5ManAlim"]));
            }
            set {
                this["XB3_CM5ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB3_CM6ManAlim {
            get {
                return ((int)(this["XB3_CM6ManAlim"]));
            }
            set {
                this["XB3_CM6ManAlim"] = value;
            }
        }
    }
}
