//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M017_Su : global::System.Configuration.ApplicationSettingsBase {
        
        private static M017_Su defaultInstance = ((M017_Su)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M017_Su())));
        
        public static M017_Su Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_SuKantar {
            get {
                return ((int)(this["XB4_SuKantar"]));
            }
            set {
                this["XB4_SuKantar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SuLoadCelldenGelen {
            get {
                return ((int)(this["SuLoadCelldenGelen"]));
            }
            set {
                this["SuLoadCelldenGelen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_Su1AManAlin {
            get {
                return ((int)(this["XB4_Su1AManAlin"]));
            }
            set {
                this["XB4_Su1AManAlin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_Su2AManAlin {
            get {
                return ((int)(this["XB4_Su2AManAlin"]));
            }
            set {
                this["XB4_Su2AManAlin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_Su3AManAlin {
            get {
                return ((int)(this["XB4_Su3AManAlin"]));
            }
            set {
                this["XB4_Su3AManAlin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_Su4AManAlin {
            get {
                return ((int)(this["XB4_Su4AManAlin"]));
            }
            set {
                this["XB4_Su4AManAlin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB4_AraKantarSu {
            get {
                return ((int)(this["XB4_AraKantarSu"]));
            }
            set {
                this["XB4_AraKantarSu"] = value;
            }
        }
    }
}
