//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M018_Katki : global::System.Configuration.ApplicationSettingsBase {
        
        private static M018_Katki defaultInstance = ((M018_Katki)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M018_Katki())));
        
        public static M018_Katki Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_KatKantar {
            get {
                return ((double)(this["XB5_KatKantar"]));
            }
            set {
                this["XB5_KatKantar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KatkiLoadCelldenGelen {
            get {
                return ((double)(this["KatkiLoadCelldenGelen"]));
            }
            set {
                this["KatkiLoadCelldenGelen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K1ManAlim {
            get {
                return ((double)(this["XB5_K1ManAlim"]));
            }
            set {
                this["XB5_K1ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K2ManAlim {
            get {
                return ((double)(this["XB5_K2ManAlim"]));
            }
            set {
                this["XB5_K2ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K3ManAlim {
            get {
                return ((double)(this["XB5_K3ManAlim"]));
            }
            set {
                this["XB5_K3ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K4ManAlim {
            get {
                return ((double)(this["XB5_K4ManAlim"]));
            }
            set {
                this["XB5_K4ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K5ManAlim {
            get {
                return ((double)(this["XB5_K5ManAlim"]));
            }
            set {
                this["XB5_K5ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_K6ManAlim {
            get {
                return ((double)(this["XB5_K6ManAlim"]));
            }
            set {
                this["XB5_K6ManAlim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB5_AraKantarKatki {
            get {
                return ((double)(this["XB5_AraKantarKatki"]));
            }
            set {
                this["XB5_AraKantarKatki"] = value;
            }
        }
    }
}
