//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class M101_Array : global::System.Configuration.ApplicationSettingsBase {
        
        private static M101_Array defaultInstance = ((M101_Array)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new M101_Array())));
        
        public static M101_Array Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Su1_ArrayCount_31 {
            get {
                return ((double)(this["Verilen_Su1_ArrayCount_31"]));
            }
            set {
                this["Verilen_Su1_ArrayCount_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Su2_ArrayCount_32 {
            get {
                return ((double)(this["Verilen_Su2_ArrayCount_32"]));
            }
            set {
                this["Verilen_Su2_ArrayCount_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Su3_ArrayCount_33 {
            get {
                return ((double)(this["Verilen_Su3_ArrayCount_33"]));
            }
            set {
                this["Verilen_Su3_ArrayCount_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Cimento1_ArrayCount_11 {
            get {
                return ((double)(this["Verilen_Cimento1_ArrayCount_11"]));
            }
            set {
                this["Verilen_Cimento1_ArrayCount_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Cimento2_ArrayCount_12 {
            get {
                return ((double)(this["Verilen_Cimento2_ArrayCount_12"]));
            }
            set {
                this["Verilen_Cimento2_ArrayCount_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Cimento3_ArrayCount_13 {
            get {
                return ((double)(this["Verilen_Cimento3_ArrayCount_13"]));
            }
            set {
                this["Verilen_Cimento3_ArrayCount_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Cimento4_ArrayCount_14 {
            get {
                return ((double)(this["Verilen_Cimento4_ArrayCount_14"]));
            }
            set {
                this["Verilen_Cimento4_ArrayCount_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Agrega1_ArrayCount_01 {
            get {
                return ((double)(this["Verilen_Agrega1_ArrayCount_01"]));
            }
            set {
                this["Verilen_Agrega1_ArrayCount_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Agrega2_ArrayCount_02 {
            get {
                return ((double)(this["Verilen_Agrega2_ArrayCount_02"]));
            }
            set {
                this["Verilen_Agrega2_ArrayCount_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Agrega3_ArrayCount_03 {
            get {
                return ((double)(this["Verilen_Agrega3_ArrayCount_03"]));
            }
            set {
                this["Verilen_Agrega3_ArrayCount_03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Agrega4_ArrayCount_04 {
            get {
                return ((double)(this["Verilen_Agrega4_ArrayCount_04"]));
            }
            set {
                this["Verilen_Agrega4_ArrayCount_04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Agrega5_ArrayCount_05 {
            get {
                return ((double)(this["Verilen_Agrega5_ArrayCount_05"]));
            }
            set {
                this["Verilen_Agrega5_ArrayCount_05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Katki1_ArrayCount_21 {
            get {
                return ((double)(this["Verilen_Katki1_ArrayCount_21"]));
            }
            set {
                this["Verilen_Katki1_ArrayCount_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Katki2_ArrayCount_22 {
            get {
                return ((double)(this["Verilen_Katki2_ArrayCount_22"]));
            }
            set {
                this["Verilen_Katki2_ArrayCount_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Katki3_ArrayCount_23 {
            get {
                return ((double)(this["Verilen_Katki3_ArrayCount_23"]));
            }
            set {
                this["Verilen_Katki3_ArrayCount_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Katki4_ArrayCount_24 {
            get {
                return ((double)(this["Verilen_Katki4_ArrayCount_24"]));
            }
            set {
                this["Verilen_Katki4_ArrayCount_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Katki5_ArrayCount_25 {
            get {
                return ((double)(this["Verilen_Katki5_ArrayCount_25"]));
            }
            set {
                this["Verilen_Katki5_ArrayCount_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Agrega1_ArrayCount_1 {
            get {
                return ((double)(this["ToplamIstenen_Agrega1_ArrayCount_1"]));
            }
            set {
                this["ToplamIstenen_Agrega1_ArrayCount_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Agrega2_ArrayCount_2 {
            get {
                return ((double)(this["ToplamIstenen_Agrega2_ArrayCount_2"]));
            }
            set {
                this["ToplamIstenen_Agrega2_ArrayCount_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Agrega3_ArrayCount_3 {
            get {
                return ((double)(this["ToplamIstenen_Agrega3_ArrayCount_3"]));
            }
            set {
                this["ToplamIstenen_Agrega3_ArrayCount_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Agrega4_ArrayCount_4 {
            get {
                return ((double)(this["ToplamIstenen_Agrega4_ArrayCount_4"]));
            }
            set {
                this["ToplamIstenen_Agrega4_ArrayCount_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Agrega5_ArrayCount_5 {
            get {
                return ((double)(this["ToplamIstenen_Agrega5_ArrayCount_5"]));
            }
            set {
                this["ToplamIstenen_Agrega5_ArrayCount_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Cimento1_ArrayCount_11 {
            get {
                return ((double)(this["ToplamIstenen_Cimento1_ArrayCount_11"]));
            }
            set {
                this["ToplamIstenen_Cimento1_ArrayCount_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Cimento2_ArrayCount_12 {
            get {
                return ((double)(this["ToplamIstenen_Cimento2_ArrayCount_12"]));
            }
            set {
                this["ToplamIstenen_Cimento2_ArrayCount_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Cimento3_ArrayCount_13 {
            get {
                return ((double)(this["ToplamIstenen_Cimento3_ArrayCount_13"]));
            }
            set {
                this["ToplamIstenen_Cimento3_ArrayCount_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Cimento4_ArrayCount_14 {
            get {
                return ((double)(this["ToplamIstenen_Cimento4_ArrayCount_14"]));
            }
            set {
                this["ToplamIstenen_Cimento4_ArrayCount_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Cimento5_ArrayCount_15 {
            get {
                return ((double)(this["ToplamIstenen_Cimento5_ArrayCount_15"]));
            }
            set {
                this["ToplamIstenen_Cimento5_ArrayCount_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Katki1_ArrayCount_21 {
            get {
                return ((double)(this["ToplamIstenen_Katki1_ArrayCount_21"]));
            }
            set {
                this["ToplamIstenen_Katki1_ArrayCount_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Katki2_ArrayCount_22 {
            get {
                return ((double)(this["ToplamIstenen_Katki2_ArrayCount_22"]));
            }
            set {
                this["ToplamIstenen_Katki2_ArrayCount_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Katki3_ArrayCount_23 {
            get {
                return ((double)(this["ToplamIstenen_Katki3_ArrayCount_23"]));
            }
            set {
                this["ToplamIstenen_Katki3_ArrayCount_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Katki4_ArrayCount_24 {
            get {
                return ((double)(this["ToplamIstenen_Katki4_ArrayCount_24"]));
            }
            set {
                this["ToplamIstenen_Katki4_ArrayCount_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Katki5_ArrayCount_25 {
            get {
                return ((double)(this["ToplamIstenen_Katki5_ArrayCount_25"]));
            }
            set {
                this["ToplamIstenen_Katki5_ArrayCount_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Su1_ArrayCount_31 {
            get {
                return ((double)(this["ToplamIstenen_Su1_ArrayCount_31"]));
            }
            set {
                this["ToplamIstenen_Su1_ArrayCount_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Su2_ArrayCount_32 {
            get {
                return ((double)(this["ToplamIstenen_Su2_ArrayCount_32"]));
            }
            set {
                this["ToplamIstenen_Su2_ArrayCount_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToplamIstenen_Su3_ArrayCount_33 {
            get {
                return ((double)(this["ToplamIstenen_Su3_ArrayCount_33"]));
            }
            set {
                this["ToplamIstenen_Su3_ArrayCount_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Verilen_Cimento5_ArrayCount_15 {
            get {
                return ((double)(this["Verilen_Cimento5_ArrayCount_15"]));
            }
            set {
                this["Verilen_Cimento5_ArrayCount_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Agrega1_ArrayCount_1 {
            get {
                return ((double)(this["ManualUretimMiktari_Agrega1_ArrayCount_1"]));
            }
            set {
                this["ManualUretimMiktari_Agrega1_ArrayCount_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Agrega2_ArrayCount_2 {
            get {
                return ((double)(this["ManualUretimMiktari_Agrega2_ArrayCount_2"]));
            }
            set {
                this["ManualUretimMiktari_Agrega2_ArrayCount_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Agrega3_ArrayCount_3 {
            get {
                return ((double)(this["ManualUretimMiktari_Agrega3_ArrayCount_3"]));
            }
            set {
                this["ManualUretimMiktari_Agrega3_ArrayCount_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Agrega4_ArrayCount_4 {
            get {
                return ((double)(this["ManualUretimMiktari_Agrega4_ArrayCount_4"]));
            }
            set {
                this["ManualUretimMiktari_Agrega4_ArrayCount_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Agrega5_ArrayCount_5 {
            get {
                return ((double)(this["ManualUretimMiktari_Agrega5_ArrayCount_5"]));
            }
            set {
                this["ManualUretimMiktari_Agrega5_ArrayCount_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Katki1_ArrayCount_21 {
            get {
                return ((double)(this["ManualUretimMiktari_Katki1_ArrayCount_21"]));
            }
            set {
                this["ManualUretimMiktari_Katki1_ArrayCount_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Katki2_ArrayCount_22 {
            get {
                return ((double)(this["ManualUretimMiktari_Katki2_ArrayCount_22"]));
            }
            set {
                this["ManualUretimMiktari_Katki2_ArrayCount_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Katki3_ArrayCount_23 {
            get {
                return ((double)(this["ManualUretimMiktari_Katki3_ArrayCount_23"]));
            }
            set {
                this["ManualUretimMiktari_Katki3_ArrayCount_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Katki4_ArrayCount_24 {
            get {
                return ((double)(this["ManualUretimMiktari_Katki4_ArrayCount_24"]));
            }
            set {
                this["ManualUretimMiktari_Katki4_ArrayCount_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Katki5_ArrayCount_25 {
            get {
                return ((double)(this["ManualUretimMiktari_Katki5_ArrayCount_25"]));
            }
            set {
                this["ManualUretimMiktari_Katki5_ArrayCount_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Su1_ArrayCount_31 {
            get {
                return ((double)(this["ManualUretimMiktari_Su1_ArrayCount_31"]));
            }
            set {
                this["ManualUretimMiktari_Su1_ArrayCount_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Su2_ArrayCount_32 {
            get {
                return ((double)(this["ManualUretimMiktari_Su2_ArrayCount_32"]));
            }
            set {
                this["ManualUretimMiktari_Su2_ArrayCount_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Su3_ArrayCount_33 {
            get {
                return ((double)(this["ManualUretimMiktari_Su3_ArrayCount_33"]));
            }
            set {
                this["ManualUretimMiktari_Su3_ArrayCount_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Cimento1_ArrayCount_11 {
            get {
                return ((double)(this["ManualUretimMiktari_Cimento1_ArrayCount_11"]));
            }
            set {
                this["ManualUretimMiktari_Cimento1_ArrayCount_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Cimento2_ArrayCount_12 {
            get {
                return ((double)(this["ManualUretimMiktari_Cimento2_ArrayCount_12"]));
            }
            set {
                this["ManualUretimMiktari_Cimento2_ArrayCount_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Cimento3_ArrayCount_13 {
            get {
                return ((double)(this["ManualUretimMiktari_Cimento3_ArrayCount_13"]));
            }
            set {
                this["ManualUretimMiktari_Cimento3_ArrayCount_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Cimento4_ArrayCount_14 {
            get {
                return ((double)(this["ManualUretimMiktari_Cimento4_ArrayCount_14"]));
            }
            set {
                this["ManualUretimMiktari_Cimento4_ArrayCount_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ManualUretimMiktari_Cimento5_ArrayCount_15 {
            get {
                return ((double)(this["ManualUretimMiktari_Cimento5_ArrayCount_15"]));
            }
            set {
                this["ManualUretimMiktari_Cimento5_ArrayCount_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Agrega1_ArrayCount_1 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Agrega1_ArrayCount_1"]));
            }
            set {
                this["YariOtoUretimMiktari_Agrega1_ArrayCount_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Agrega2_ArrayCount_2 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Agrega2_ArrayCount_2"]));
            }
            set {
                this["YariOtoUretimMiktari_Agrega2_ArrayCount_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Agrega3_ArrayCount_3 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Agrega3_ArrayCount_3"]));
            }
            set {
                this["YariOtoUretimMiktari_Agrega3_ArrayCount_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Agrega4_ArrayCount_4 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Agrega4_ArrayCount_4"]));
            }
            set {
                this["YariOtoUretimMiktari_Agrega4_ArrayCount_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Agrega5_ArrayCount_5 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Agrega5_ArrayCount_5"]));
            }
            set {
                this["YariOtoUretimMiktari_Agrega5_ArrayCount_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Cimento1_ArrayCount_11 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Cimento1_ArrayCount_11"]));
            }
            set {
                this["YariOtoUretimMiktari_Cimento1_ArrayCount_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Cimento2_ArrayCount_12 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Cimento2_ArrayCount_12"]));
            }
            set {
                this["YariOtoUretimMiktari_Cimento2_ArrayCount_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Cimento3_ArrayCount_13 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Cimento3_ArrayCount_13"]));
            }
            set {
                this["YariOtoUretimMiktari_Cimento3_ArrayCount_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Cimento4_ArrayCount_14 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Cimento4_ArrayCount_14"]));
            }
            set {
                this["YariOtoUretimMiktari_Cimento4_ArrayCount_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Cimento5_ArrayCount_15 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Cimento5_ArrayCount_15"]));
            }
            set {
                this["YariOtoUretimMiktari_Cimento5_ArrayCount_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Katki1_ArrayCount_21 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Katki1_ArrayCount_21"]));
            }
            set {
                this["YariOtoUretimMiktari_Katki1_ArrayCount_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Katki2_ArrayCount_22 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Katki2_ArrayCount_22"]));
            }
            set {
                this["YariOtoUretimMiktari_Katki2_ArrayCount_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Katki3_ArrayCount_23 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Katki3_ArrayCount_23"]));
            }
            set {
                this["YariOtoUretimMiktari_Katki3_ArrayCount_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Katki4_ArrayCount_24 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Katki4_ArrayCount_24"]));
            }
            set {
                this["YariOtoUretimMiktari_Katki4_ArrayCount_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Katki5_ArrayCount_25 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Katki5_ArrayCount_25"]));
            }
            set {
                this["YariOtoUretimMiktari_Katki5_ArrayCount_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Su1_ArrayCount_31 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Su1_ArrayCount_31"]));
            }
            set {
                this["YariOtoUretimMiktari_Su1_ArrayCount_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Su2_ArrayCount_32 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Su2_ArrayCount_32"]));
            }
            set {
                this["YariOtoUretimMiktari_Su2_ArrayCount_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double YariOtoUretimMiktari_Su3_ArrauCount_33 {
            get {
                return ((double)(this["YariOtoUretimMiktari_Su3_ArrauCount_33"]));
            }
            set {
                this["YariOtoUretimMiktari_Su3_ArrauCount_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZamanTarihDizisi_Hour_ArrayCount_0 {
            get {
                return ((int)(this["ZamanTarihDizisi_Hour_ArrayCount_0"]));
            }
            set {
                this["ZamanTarihDizisi_Hour_ArrayCount_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZamanTarihDizisi_Min_ArrayCount_1 {
            get {
                return ((int)(this["ZamanTarihDizisi_Min_ArrayCount_1"]));
            }
            set {
                this["ZamanTarihDizisi_Min_ArrayCount_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZamanTarihDizisi_Year_ArrayCount_2 {
            get {
                return ((int)(this["ZamanTarihDizisi_Year_ArrayCount_2"]));
            }
            set {
                this["ZamanTarihDizisi_Year_ArrayCount_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZamanTarihDizisi_Mon_ArrayCount_3 {
            get {
                return ((int)(this["ZamanTarihDizisi_Mon_ArrayCount_3"]));
            }
            set {
                this["ZamanTarihDizisi_Mon_ArrayCount_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZamanTarihDizisi_Day_ArrayCount_4 {
            get {
                return ((int)(this["ZamanTarihDizisi_Day_ArrayCount_4"]));
            }
            set {
                this["ZamanTarihDizisi_Day_ArrayCount_4"] = value;
            }
        }
    }
}
