//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class R004_Parametreler : global::System.Configuration.ApplicationSettingsBase {
        
        private static R004_Parametreler defaultInstance = ((R004_Parametreler)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new R004_Parametreler())));
        
        public static R004_Parametreler Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QM_SeriesEnable {
            get {
                return ((bool)(this["QM_SeriesEnable"]));
            }
            set {
                this["QM_SeriesEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Compact_SeriesEnable {
            get {
                return ((bool)(this["Compact_SeriesEnable"]));
            }
            set {
                this["Compact_SeriesEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_AgCiftKapakSecim {
            get {
                return ((bool)(this["XB111_AgCiftKapakSecim"]));
            }
            set {
                this["XB111_AgCiftKapakSecim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_YaglamaOto {
            get {
                return ((bool)(this["XB111_YaglamaOto"]));
            }
            set {
                this["XB111_YaglamaOto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_Ag1NemOtoMan {
            get {
                return ((bool)(this["XB111_Ag1NemOtoMan"]));
            }
            set {
                this["XB111_Ag1NemOtoMan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_Ag2NemOtoMan {
            get {
                return ((bool)(this["XB111_Ag2NemOtoMan"]));
            }
            set {
                this["XB111_Ag2NemOtoMan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_Ag3NemOtoMan {
            get {
                return ((bool)(this["XB111_Ag3NemOtoMan"]));
            }
            set {
                this["XB111_Ag3NemOtoMan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_Ag4NemOtoMan {
            get {
                return ((bool)(this["XB111_Ag4NemOtoMan"]));
            }
            set {
                this["XB111_Ag4NemOtoMan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_SecilenMikserTW {
            get {
                return ((bool)(this["s_SecilenMikserTW"]));
            }
            set {
                this["s_SecilenMikserTW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_SantralTipiWord {
            get {
                return ((int)(this["s_SantralTipiWord"]));
            }
            set {
                this["s_SantralTipiWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_VibratorluBeslemeSayisi {
            get {
                return ((int)(this["s_VibratorluBeslemeSayisi"]));
            }
            set {
                this["s_VibratorluBeslemeSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_AgKantarKapasite {
            get {
                return ((int)(this["XB19_AgKantarKapasite"]));
            }
            set {
                this["XB19_AgKantarKapasite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_CMKantarKapasite {
            get {
                return ((int)(this["XB19_CMKantarKapasite"]));
            }
            set {
                this["XB19_CMKantarKapasite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_SuKantarKapasite {
            get {
                return ((int)(this["XB19_SuKantarKapasite"]));
            }
            set {
                this["XB19_SuKantarKapasite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_KatkiKantarKapasite {
            get {
                return ((int)(this["XB19_KatkiKantarKapasite"]));
            }
            set {
                this["XB19_KatkiKantarKapasite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamMikserAsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamMikserAsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamMikserAsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamHelezon1AsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamHelezon1AsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamHelezon1AsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamHelezon2AsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamHelezon2AsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamHelezon2AsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamHelezon3AsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamHelezon3AsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamHelezon3AsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamHelezon4AsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamHelezon4AsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamHelezon4AsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB19_ParamHelezon5AsiriAkimLimit {
            get {
                return ((int)(this["XB19_ParamHelezon5AsiriAkimLimit"]));
            }
            set {
                this["XB19_ParamHelezon5AsiriAkimLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB19_ParamMikserKapasite {
            get {
                return ((float)(this["XB19_ParamMikserKapasite"]));
            }
            set {
                this["XB19_ParamMikserKapasite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB158_AnaAkimTrafoOrani {
            get {
                return ((float)(this["XB158_AnaAkimTrafoOrani"]));
            }
            set {
                this["XB158_AnaAkimTrafoOrani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB158_MikserAkimTrafoOrani {
            get {
                return ((float)(this["XB158_MikserAkimTrafoOrani"]));
            }
            set {
                this["XB158_MikserAkimTrafoOrani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB158_HelezonAkimTrafoOrani {
            get {
                return ((float)(this["XB158_HelezonAkimTrafoOrani"]));
            }
            set {
                this["XB158_HelezonAkimTrafoOrani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB19_SlumpMetreKatsayi {
            get {
                return ((float)(this["XB19_SlumpMetreKatsayi"]));
            }
            set {
                this["XB19_SlumpMetreKatsayi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float XB19_HelezonKatsayi {
            get {
                return ((float)(this["XB19_HelezonKatsayi"]));
            }
            set {
                this["XB19_HelezonKatsayi"] = value;
            }
        }
    }
}
