//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class R006_Uretim : global::System.Configuration.ApplicationSettingsBase {
        
        private static R006_Uretim defaultInstance = ((R006_Uretim)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new R006_Uretim())));
        
        public static R006_Uretim Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_AgregaAlindi {
            get {
                return ((bool)(this["XB111_AgregaAlindi"]));
            }
            set {
                this["XB111_AgregaAlindi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_CimentoAlindi {
            get {
                return ((bool)(this["XB111_CimentoAlindi"]));
            }
            set {
                this["XB111_CimentoAlindi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_SuAlindi {
            get {
                return ((bool)(this["XB111_SuAlindi"]));
            }
            set {
                this["XB111_SuAlindi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_KatkiAlindi {
            get {
                return ((bool)(this["XB111_KatkiAlindi"]));
            }
            set {
                this["XB111_KatkiAlindi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_AgregaBasla {
            get {
                return ((bool)(this["XB111_AgregaBasla"]));
            }
            set {
                this["XB111_AgregaBasla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_MalzemeAlimBasla {
            get {
                return ((bool)(this["XB111_MalzemeAlimBasla"]));
            }
            set {
                this["XB111_MalzemeAlimBasla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeriUretim {
            get {
                return ((bool)(this["SeriUretim"]));
            }
            set {
                this["SeriUretim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_UretimReset {
            get {
                return ((bool)(this["XB111_UretimReset"]));
            }
            set {
                this["XB111_UretimReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XB111_Uretim {
            get {
                return ((bool)(this["XB111_Uretim"]));
            }
            set {
                this["XB111_Uretim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YapilanTurSifirlandi {
            get {
                return ((bool)(this["YapilanTurSifirlandi"]));
            }
            set {
                this["YapilanTurSifirlandi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool v_Yrd_YariModUretimDevam {
            get {
                return ((bool)(this["v_Yrd_YariModUretimDevam"]));
            }
            set {
                this["v_Yrd_YariModUretimDevam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_ManualKayitArsivAl {
            get {
                return ((bool)(this["s_ManualKayitArsivAl"]));
            }
            set {
                this["s_ManualKayitArsivAl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_ManuelUretimDisplayTrigger {
            get {
                return ((bool)(this["s_ManuelUretimDisplayTrigger"]));
            }
            set {
                this["s_ManuelUretimDisplayTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_AgregaKW {
            get {
                return ((int)(this["XB112_AgregaKW"]));
            }
            set {
                this["XB112_AgregaKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_CimentoKW {
            get {
                return ((int)(this["XB112_CimentoKW"]));
            }
            set {
                this["XB112_CimentoKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_SuKW {
            get {
                return ((int)(this["XB112_SuKW"]));
            }
            set {
                this["XB112_SuKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KatkiKW {
            get {
                return ((int)(this["XB112_KatkiKW"]));
            }
            set {
                this["XB112_KatkiKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_MikserKW {
            get {
                return ((int)(this["XB112_MikserKW"]));
            }
            set {
                this["XB112_MikserKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_TransferBandKW {
            get {
                return ((int)(this["XB112_TransferBandKW"]));
            }
            set {
                this["XB112_TransferBandKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KovaKW {
            get {
                return ((int)(this["XB112_KovaKW"]));
            }
            set {
                this["XB112_KovaKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_ToplamTur {
            get {
                return ((int)(this["XB112_ToplamTur"]));
            }
            set {
                this["XB112_ToplamTur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_YapilanTur {
            get {
                return ((int)(this["XB112_YapilanTur"]));
            }
            set {
                this["XB112_YapilanTur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_AgregaTur {
            get {
                return ((int)(this["XB112_AgregaTur"]));
            }
            set {
                this["XB112_AgregaTur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_MalzemeTur {
            get {
                return ((int)(this["XB112_MalzemeTur"]));
            }
            set {
                this["XB112_MalzemeTur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KaristirmaSureRecete {
            get {
                return ((int)(this["XB112_KaristirmaSureRecete"]));
            }
            set {
                this["XB112_KaristirmaSureRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_BosaltilmaRecete {
            get {
                return ((int)(this["XB112_BosaltilmaRecete"]));
            }
            set {
                this["XB112_BosaltilmaRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_CimentoGecikmeRecete {
            get {
                return ((int)(this["XB112_CimentoGecikmeRecete"]));
            }
            set {
                this["XB112_CimentoGecikmeRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_SuGecikmeRecete {
            get {
                return ((int)(this["XB112_SuGecikmeRecete"]));
            }
            set {
                this["XB112_SuGecikmeRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KatkiGecikmeRecete {
            get {
                return ((int)(this["XB112_KatkiGecikmeRecete"]));
            }
            set {
                this["XB112_KatkiGecikmeRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KovaAraYurumeSuresi {
            get {
                return ((int)(this["XB112_KovaAraYurumeSuresi"]));
            }
            set {
                this["XB112_KovaAraYurumeSuresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KovaMaxYurumeSuresi {
            get {
                return ((int)(this["XB112_KovaMaxYurumeSuresi"]));
            }
            set {
                this["XB112_KovaMaxYurumeSuresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_BosaltilanSure {
            get {
                return ((int)(this["XB112_BosaltilanSure"]));
            }
            set {
                this["XB112_BosaltilanSure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_KaristirilanSure {
            get {
                return ((int)(this["XB112_KaristirilanSure"]));
            }
            set {
                this["XB112_KaristirilanSure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UretimPlaniDataGrid {
            get {
                return ((int)(this["UretimPlaniDataGrid"]));
            }
            set {
                this["UretimPlaniDataGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int XB112_AraBantKW {
            get {
                return ((int)(this["XB112_AraBantKW"]));
            }
            set {
                this["XB112_AraBantKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_MiktarYapilan {
            get {
                return ((double)(this["XB19_MiktarYapilan"]));
            }
            set {
                this["XB19_MiktarYapilan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_Miktar {
            get {
                return ((double)(this["XB19_Miktar"]));
            }
            set {
                this["XB19_Miktar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_ToplamYapilanMiktar {
            get {
                return ((double)(this["XB19_ToplamYapilanMiktar"]));
            }
            set {
                this["XB19_ToplamYapilanMiktar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB1_ReceteKatsayi {
            get {
                return ((double)(this["XB1_ReceteKatsayi"]));
            }
            set {
                this["XB1_ReceteKatsayi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReadWriteStatus {
            get {
                return ((bool)(this["ReadWriteStatus"]));
            }
            set {
                this["ReadWriteStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XB19_GunlukToplamYapilanMiktar {
            get {
                return ((double)(this["XB19_GunlukToplamYapilanMiktar"]));
            }
            set {
                this["XB19_GunlukToplamYapilanMiktar"] = value;
            }
        }
    }
}
