//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class S000_Konfigrator_Tag : global::System.Configuration.ApplicationSettingsBase {
        
        private static S000_Konfigrator_Tag defaultInstance = ((S000_Konfigrator_Tag)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new S000_Konfigrator_Tag())));
        
        public static S000_Konfigrator_Tag Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenSantralTipi {
            get {
                return ((int)(this["SecilenSantralTipi"]));
            }
            set {
                this["SecilenSantralTipi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KovaSecildi {
            get {
                return ((bool)(this["KovaSecildi"]));
            }
            set {
                this["KovaSecildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransferbandıSecildi {
            get {
                return ((bool)(this["TransferbandıSecildi"]));
            }
            set {
                this["TransferbandıSecildi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DuzTipTartıKonveyor {
            get {
                return ((bool)(this["DuzTipTartıKonveyor"]));
            }
            set {
                this["DuzTipTartıKonveyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool T_TipliTartiKonveyor {
            get {
                return ((bool)(this["T_TipliTartiKonveyor"]));
            }
            set {
                this["T_TipliTartiKonveyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MikserNemOlcerVar {
            get {
                return ((bool)(this["MikserNemOlcerVar"]));
            }
            set {
                this["MikserNemOlcerVar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BetonTasimaVarYok {
            get {
                return ((bool)(this["BetonTasimaVarYok"]));
            }
            set {
                this["BetonTasimaVarYok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenSantralModeli {
            get {
                return ((int)(this["SecilenSantralModeli"]));
            }
            set {
                this["SecilenSantralModeli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg1Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg1Var_Yok"]));
            }
            set {
                this["HassasKapakAg1Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg2Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg2Var_Yok"]));
            }
            set {
                this["HassasKapakAg2Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg3Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg3Var_Yok"]));
            }
            set {
                this["HassasKapakAg3Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg4Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg4Var_Yok"]));
            }
            set {
                this["HassasKapakAg4Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg5Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg5Var_Yok"]));
            }
            set {
                this["HassasKapakAg5Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HassasKapakAg6Var_Yok {
            get {
                return ((bool)(this["HassasKapakAg6Var_Yok"]));
            }
            set {
                this["HassasKapakAg6Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg1Var_Yok {
            get {
                return ((bool)(this["VibratorAg1Var_Yok"]));
            }
            set {
                this["VibratorAg1Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg2Var_Yok {
            get {
                return ((bool)(this["VibratorAg2Var_Yok"]));
            }
            set {
                this["VibratorAg2Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg3Var_Yok {
            get {
                return ((bool)(this["VibratorAg3Var_Yok"]));
            }
            set {
                this["VibratorAg3Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg4Var_Yok {
            get {
                return ((bool)(this["VibratorAg4Var_Yok"]));
            }
            set {
                this["VibratorAg4Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg5Var_Yok {
            get {
                return ((bool)(this["VibratorAg5Var_Yok"]));
            }
            set {
                this["VibratorAg5Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VibratorAg6Var_Yok {
            get {
                return ((bool)(this["VibratorAg6Var_Yok"]));
            }
            set {
                this["VibratorAg6Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg1Var_Yok {
            get {
                return ((bool)(this["NemolcerAg1Var_Yok"]));
            }
            set {
                this["NemolcerAg1Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg2Var_Yok {
            get {
                return ((bool)(this["NemolcerAg2Var_Yok"]));
            }
            set {
                this["NemolcerAg2Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg3Var_Yok {
            get {
                return ((bool)(this["NemolcerAg3Var_Yok"]));
            }
            set {
                this["NemolcerAg3Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg4Var_Yok {
            get {
                return ((bool)(this["NemolcerAg4Var_Yok"]));
            }
            set {
                this["NemolcerAg4Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg5Var_Yok {
            get {
                return ((bool)(this["NemolcerAg5Var_Yok"]));
            }
            set {
                this["NemolcerAg5Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NemolcerAg6Var_Yok {
            get {
                return ((bool)(this["NemolcerAg6Var_Yok"]));
            }
            set {
                this["NemolcerAg6Var_Yok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenBunkerSayisi {
            get {
                return ((int)(this["SecilenBunkerSayisi"]));
            }
            set {
                this["SecilenBunkerSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TartiKonveyorKapasitesi {
            get {
                return ((int)(this["TartiKonveyorKapasitesi"]));
            }
            set {
                this["TartiKonveyorKapasitesi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenCimentoSayisi {
            get {
                return ((int)(this["SecilenCimentoSayisi"]));
            }
            set {
                this["SecilenCimentoSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecilenSinifMM {
            get {
                return ((bool)(this["SecilenSinifMM"]));
            }
            set {
                this["SecilenSinifMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TorbaliHelezonSecimi {
            get {
                return ((bool)(this["TorbaliHelezonSecimi"]));
            }
            set {
                this["TorbaliHelezonSecimi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int KatkiSayisi {
            get {
                return ((int)(this["KatkiSayisi"]));
            }
            set {
                this["KatkiSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KatkiKantarVarYok1 {
            get {
                return ((bool)(this["KatkiKantarVarYok1"]));
            }
            set {
                this["KatkiKantarVarYok1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KatkiKantarVarYok2 {
            get {
                return ((bool)(this["KatkiKantarVarYok2"]));
            }
            set {
                this["KatkiKantarVarYok2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KatkiKantarVarYok3 {
            get {
                return ((bool)(this["KatkiKantarVarYok3"]));
            }
            set {
                this["KatkiKantarVarYok3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KatkiKantarVarYok4 {
            get {
                return ((bool)(this["KatkiKantarVarYok4"]));
            }
            set {
                this["KatkiKantarVarYok4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KatkiKantarVarYok5 {
            get {
                return ((bool)(this["KatkiKantarVarYok5"]));
            }
            set {
                this["KatkiKantarVarYok5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuKantarVarYok1 {
            get {
                return ((bool)(this["SuKantarVarYok1"]));
            }
            set {
                this["SuKantarVarYok1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuKantarVarYok2 {
            get {
                return ((bool)(this["SuKantarVarYok2"]));
            }
            set {
                this["SuKantarVarYok2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuKantarVarYok3 {
            get {
                return ((bool)(this["SuKantarVarYok3"]));
            }
            set {
                this["SuKantarVarYok3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SuSayisi {
            get {
                return ((int)(this["SuSayisi"]));
            }
            set {
                this["SuSayisi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenMixerTip {
            get {
                return ((int)(this["SecilenMixerTip"]));
            }
            set {
                this["SecilenMixerTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecilenRecete {
            get {
                return ((int)(this["SecilenRecete"]));
            }
            set {
                this["SecilenRecete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool konfigrasyonYapiliyor {
            get {
                return ((bool)(this["konfigrasyonYapiliyor"]));
            }
            set {
                this["konfigrasyonYapiliyor"] = value;
            }
        }
    }
}
