//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class S002UretimResetleme_Tag : global::System.Configuration.ApplicationSettingsBase {
        
        private static S002UretimResetleme_Tag defaultInstance = ((S002UretimResetleme_Tag)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new S002UretimResetleme_Tag())));
        
        public static S002UretimResetleme_Tag Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UretimResetleniyor {
            get {
                return ((bool)(this["UretimResetleniyor"]));
            }
            set {
                this["UretimResetleniyor"] = value;
            }
        }
    }
}
