//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElkonScada.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Sys003_UretimTags : global::System.Configuration.ApplicationSettingsBase {
        
        private static Sys003_UretimTags defaultInstance = ((Sys003_UretimTags)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Sys003_UretimTags())));
        
        public static Sys003_UretimTags Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartVerildi {
            get {
                return ((bool)(this["StartVerildi"]));
            }
            set {
                this["StartVerildi"] = value;
            }
        }
    }
}
